### ISSUE TITLE
Remove conditional code that depends on DotSpatialProjections compiler directive

### ISSUE THREAD

**Issue by FObermaier** [SharpMap/SharpMap#10]
With the introduction of `GeoAPI.ICoordinateSystemServices` interface the need for the `DotSpatalProjections` compiler directive has vanished.
We need to reflect that in the code.

**Comment by piksel** [comment]
@FObermaier I actually did this myself when trying to slim down the library. I will submit my changes to [https://github.com/piksel/SharpMap](piksel/SharpMap). How far along are you?

**Comment by FObermaier** [comment]
@piksel , thanks for your offer to help, but I seem to have removed them already all.
