### ISSUE TITLE
Proper use of TableSchema in SqlServer2008 provider

### ISSUE THREAD

**Issue by FObermaier** [SharpMap/SharpMap#11]
Currently the table schema defined in constructor argument or set via property is not evaluated correctly.

**Comment by am2222** [comment]
It seems that there are also some problems..I can  easily run this query 
`select * from [dbo].GetParcelsBythem(1,1)`
but when I add `[dbo].GetParcelsBythem(1,1)` as table name I get the error that says could not find object..It seems that the parsing table function have some problems..
