### ISSUE TITLE
Last character of label chopped off.

### ISSUE THREAD

**Issue by eiredrake** [SharpMap/SharpMap#110]
I've got a rather odd scenario here. I'm working in Windows, using VS 2017 and framework 4.6.1. Essentially I have been putting labellayers into my map and have been noticing that in certain fonts, the last character is getting lopped off. I thought it might just be something in the code I'd written so I created a test method that just assembles the label layer (with text of: (<fontname> <size>pt) The Quick Brown Fox)  and inserts it into the mapbox. I don't think I'm doing anything incorrectly or anything special with it but the outcome is off. In the ones that fail, the 'x' in fox is always missing. If I change the text or make it longer or shorter it's always the final character. Debugging down into where I am populating the FeatureDataTable's row with the text, I can see the text as there in it's entirety before I shove it into a provider. So it's not me doing something before I hand the text off to Sharpmap.

I've written test code that basically iterates through all of the fonts on my system, creates a layer, populates it and sticks it into the mapbox and then prompts the user to see if the on screen layer is correct. The results are output to a CSV file. Originally I thought it was dependent on font size, but when i re-tested 10 point fonts almost all of them failed.

I suppose I could put a space or period at the end of the label text and let it be chopped off but that still leaves something odd going on.

scratch that: putting a space at the end of the text didn't change anything. A period does, but naturally the period is chopped off because it's the last character.

Does anyone have any ideas on what i might be doing wrong or might this be something wrong with whatever is doing the screen measurements within Sharpmap?

Below is the code i'm currently using as a test case. Attached are the results of my test in a CSV file (as output by CSVHelper and an image showing the the map output
![map 1](https://user-images.githubusercontent.com/10224957/44871625-d8556080-ac82-11e8-916c-7cad308dee5c.png)
![map 2](https://user-images.githubusercontent.com/10224957/44871629-da1f2400-ac82-11e8-977d-0380260b1581.png)
[FontTests.xlsx](https://github.com/SharpMap/SharpMap/files/2337425/FontTests.xlsx)

.

```
private void labelTestToolStripMenuItem_Click(object sender, EventArgs e)
{
	var outputText = "The quick brown fox.";

	var fontNames = FontFamily.Families.Select(font => font.Name).ToArray();
	var fontCount = fontNames.Count();

	var clientRectangle = this.mapBox.ClientRectangle;

	var xBuffer = 10;
	var yBuffer = 10;
	var x = xBuffer;
	var y = yBuffer;

	var fontSize = 10;

	var fonttestResults = new List<FontTestResult>();
	for(var index = 0; index < fontCount; index++)
	{
		var fontName = fontNames.ElementAt(index);

		var location = this.mapBox.Map.ImageToWorld(new PointF(x, y));
		var geometry = new NetTopologySuite.Geometries.Point(location.X, location.Y);

		var textSize = InsertLayer(geometry, fontName, fontSize, outputText);
		System.Threading.Thread.Sleep(1000);
		this.mapBox.Refresh();

		var resultButton = MessageBox.Show(string.Format("Did the font {0} of {1}  {2} at {3} pt work? \r\n\r\nHit [Yes] if it did\r\nHit [No] if it didn't\r\nHit [Cancel] to cancel",index, fontCount, fontName, fontSize), "Continue", MessageBoxButtons.YesNoCancel);
		if (resultButton != DialogResult.Cancel)
		{
			x += Convert.ToInt32(textSize.Width) + xBuffer;
			if (!(x < clientRectangle.Width - textSize.Width - xBuffer))
			{
				x = xBuffer;
				y += yBuffer + Convert.ToInt32(textSize.Height);
			}

			if (!(y < clientRectangle.Height - textSize.Height - yBuffer))
			{
				x = xBuffer;
				y = yBuffer;

				this.mapBox.Map.Layers.Clear();
				this.mapBox.Refresh();
			}

			if (resultButton == DialogResult.Yes)
				fonttestResults.Add(new FontTestResult(index, fontName, fontSize, true));
			else
				fonttestResults.Add(new FontTestResult(index, fontName, fontSize, false));
		}
		else
			break;
	}


	using (var stream = new FileStream(@"C:\Temp\FontTests.csv", FileMode.OpenOrCreate, FileAccess.Write, FileShare.None))
	{
		stream.Seek(0, SeekOrigin.End);

		using (var writer = new StreamWriter(stream))
		{
			using (var csvWriter = new CsvHelper.CsvWriter(new CsvHelper.CsvSerializer(writer)))
			{
				csvWriter.WriteRecords<FontTestResult>(fonttestResults);
			}
		}
	}
}

private SizeF InsertLayer(IGeometry geometry, string fontName, float fontSize, string labelText)
{
	var result = default(SizeF);

	labelText = string.Format("({0} {1}pt) {2}", fontName, fontSize, labelText);

	var featureTable = new SharpMap.Data.FeatureDataTable();
	featureTable.Columns.Add("LABEL", typeof(string));

	var dataRow = featureTable.NewRow();
	dataRow.Geometry = geometry;
	dataRow["LABEL"] = labelText;

	featureTable.Rows.Add(dataRow);

	var provider = new SharpMap.Data.Providers.GeometryFeatureProvider(featureTable);

	var layer = new SharpMap.Layers.LabelLayer(labelText);
	layer.DataSource = provider;
	layer.Enabled = true;
	layer.LabelColumn = "LABEL";

	var style = new SharpMap.Styles.LabelStyle();
	layer.Style = style;

	style.BackColor = Brushes.Transparent;
	style.ForeColor = Color.Black;
	style.Halo = Pens.Yellow;
	style.VerticalAlignment = SharpMap.Styles.LabelStyle.VerticalAlignmentEnum.Top;
	style.HorizontalAlignment = SharpMap.Styles.LabelStyle.HorizontalAlignmentEnum.Left;
	style.CollisionBuffer = new SizeF(10, 10);
	style.CollisionDetection = true;

	var font = GDISingleton.Instance.GetFont(fontName, fontSize, FontStyle.Regular);
	style.Font = font;
	
	this.mapBox.Map.Layers.Add(layer);

	var graphics = this.mapBox.CreateGraphics();
	result = graphics.MeasureString(labelText, style.Font);

	return result;
}
```

**Comment by eiredrake** [comment]
One thing I forgot to mention: I am using SharpMap 1.1.0 with SharpMap.Extensions 1.1.0 and SharpMap.UI 1.1.0 if any of that information helps.

**Comment by PABLOCORRO** [comment]
it worked for me (copied from codeplex) :
----------------------------------------------
Hello, 

the last character of labels were cut off in v1.1. not always but in case that the text of the label was longer than let's say 10 characters well.

i found the cause of this bug in 
SharpMap.Rendering.VectorRenderer.cs
        public static SizeF SizeOfString74(Graphics g, string text, Font font)
        {
            var s = g.MeasureString(text, font);
            return new SizeF(s.Width * 0.74f+1f, s.Height * 0.74f); 
        }
i replaced that by
        public static SizeF SizeOfString74(Graphics g, string text, Font font)
        {
            return g.MeasureString(text, font);
        }
after that all worked well. 

i don't know the reason for shortening width and height by 0.74 but with longer texts it does not work properly. 

Greetz
Thread #631990 | Message #1416369 | 2015-04-21

**Comment by eiredrake** [comment]
whatever it was must have been fixed. I downloaded the most recent code from the repo and wrote up a quick test harness to replicate it and can't.

I guess i'll just have to wait for the next Nuget release but I'm glad it has been dealt with either way. For now i'll just put a . at the end of my strings. 

Thanks!
