### ISSUE TITLE
Labellayer on vectorlayer with GeometryProvider as datasource

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#112]
Hello,

i'm working with a layer of helpers (points and lines). The points and lines are used as orientation when drawing polygons into maps. Because they are only temporarily necessary, the layers DataSource is a GeometryProvider.

I wonder wether it is possible to define a LabelLayer on base of geometry.UserData. Or are there other smart ways to label such a layer?

Here's my VB-code:

```VB
Dim VLayer As SharpMap.Layers.VectorLayer = Nothing
Dim geoProvider As SharpMap.Data.Providers.GeometryProvider
Dim GeomCollection As New System.Collections.Generic.List(Of GeoAPI.Geometries.IGeometry)

VLayer = New SharpMap.Layers.VectorLayer("VLayGeoPro")
geoProvider = New SharpMap.Data.Providers.GeometryProvider(New List(Of GeoAPI.Geometries.IGeometry))
VLayer.DataSource = geoProvider

Dim geom As GeoAPI.Geometries.IGeometry = GetGeomFromText("POINT (351479.72453382146 5634694.0267789941)")
geom.UserData = "Point 1"
GeomCollection.Add(geom)
geoProvider.geometries = GeomCollection
```

**Comment by joriswit** [comment]
I have not tested this, but maybe this helps:
```VB

Dim labelLayer As SharpMap.Layers.LabelLayer
labelLayer = New SharpMap.Layers.LabelLayer("MyLabel")
labelLayer.DataSource = geoProvider
labelLayer.LabelStringDelegate = Function(fdr As SharpMap.Data.FeatureDataRow)
                                     Return CStr(fdr.Geometry.UserData)
                                 End Function
```

**Comment by Lotto2** [comment]
Hi joriswit and anyone,

i didn't know, that labellayers have a LabelStringDelegate-attribute. But hellas no, it does not work. 

After 

`Mapbox.Map.Layers.Add(labelLayer) `

rendering of the map does not work no more. Only the Openstreetmap-backgroundlayer is still there.

I used SharpMap.Rendering.Thematics.FontSizeTheme.

Is there perhaps some sort of custom theme that might help?

**Comment by FObermaier** [comment]
Use a `GeometryFeatureProvider`.

**Comment by Lotto2** [comment]
GeometryFeatureProvider works fine. Great;-)

`

        'FeatureDataTable
	Dim FeatureDataTableHelpers As New SharpMap.Data.FeatureDataTable
	FeatureDataTableHelpers.TableName = "Helpers"
	FeatureDataTableHelpers.Columns.Add("Description", System.Type.GetType("System.String"))

	'GeometryFeatureProvider
	Dim geoProHelpers = New SharpMap.Data.Providers.GeometryFeatureProvider(FeatureDataTableHelpers)

	'VectorLayer
	Dim VLayerHelpers = New SharpMap.Layers.VectorLayer("Helpers")
	VLayerHelpers.DataSource = geoProHelpers
	
	'LabelLayer
	VLayerHelpersLabels = New SharpMap.Layers.LabelLayer("Helpers_Labels")
	VLayerHelpersLabels.DataSource = geoProHelpers
	VLayerHelpersLabels.LabelColumn = "Description"

	'Create geometry
	Dim gf As NetTopologySuite.Geometries.GeometryFactory = New NetTopologySuite.Geometries.GeometryFactory()
	Dim geom As GeoAPI.Geometries.IGeometry = gf.CreatePoint(New GeoAPI.Geometries.Coordinate(351479.72453382146, 5634694.0267789941))
	
	'Add row
	Dim fdr As SharpMap.Data.FeatureDataRow = FeatureDataTableHelpers.NewRow()
	fdr("Description") = "Point1"
	fdr.Geometry = geom
	FeatureDataTableHelpers.Rows.Add(fdr)

`
