### ISSUE TITLE
Raster Layer removed when apply rotation on map

### ISSUE THREAD

**Issue by Learner003** [SharpMap/SharpMap#116]
I am new to SharpMap. I am developing a simple offline map app but stuck at a point.

**What i did so far?**

1. initialized map

`SharpMap.Map map = new SharpMap.Map();`

2. Added Raster layer

`GdalRasterLayer Rasterlayer = new GdalRasterLayer("Raster", "world_raster_mod.tif"); map.layers.add(Rasterlayer);`

3. Added vector Layer

```
GeoAPI.Geometries.Coordinate[] points = new GeoAPI.Geometries.Coordinate[] { InitialCoord, DestCoord };

VectorLayer LineLayer = new VectorLayer("LineLayer");

LineLayer.DataSource = new GeometryProvider(gf.CreateLineString(points));

map.Layers.Add(LineLayer);
```

4. Applied map transoformation (because i want this line to be shown straight)

```
System.Drawing.Drawing2D.Matrix maptransform = new System.Drawing.Drawing2D.Matrix();

maptransform.RotateAt(float.Parse((-bearing).ToString()), new PointF(mapBox1.Size.Width / 2, mapBox1.Size.Height / 2));

map.MapTransform = maptransform;

mapBox1.Map = map;
```

**After map transformation raster layer is no longer visible .**
i checked SRID its fine ,

**Comment by FObermaier** [comment]
I don't see your call to `map.ZoomToExtents()` or  `map.ZoomToBox(Envelope)`

**Comment by Learner003** [comment]
I created envelope  to zoom to that envelope.
map.ZoomToBox(env);
still same issue

**Comment by Learner003** [comment]
i am not getting any exception. i debug the code its fine. but when map loads only vector data is showing but not raster.
but one thing which i experienced yesterday was i am getting raster when i zoom to specific coordinate. but not proper raster tile.
i have only one tile which is of 30KM approx. and line created from geometry factory . with in line i have some coordinates(point drawn) after each 10KM. when i zoom to that specific point raster is shown. but not complete tile. just patches . i cant get why is this happening?

**Comment by FObermaier** [comment]
I cannot reproduce your issue as stated, it might have been solved. Nonetheless, the result with an applied rotation matrix is not correct. (see #164)
