### ISSUE TITLE
Update packages in UnitTests. BruTile test serialization error

### ISSUE THREAD

**Issue by terribletim** [SharpMap/SharpMap#122]
I would like to updates packages in **UnitTests** project:

1. **BruTile** 0.18 >> 2.1

2. Add **NUnit.Runners** and **NUnitTestAdaptors** for the benefit of those without 3rd test software

The reason for updating BruTile is because of  issue _"System.Data.SQLite.Core 1.0.109.1' is not compatible with 'BruTile.Desktop 0.18.1 constraint: System.Data.SQLite.Core (= 1.0.94)"_ which must be resolved before making any changes to packages.

I have made updates in [branch on my fork](https://github.com/terribletim/SharpMap/tree/unittest_packageupdates), but various Map and BruTile tests are now failing. In particular: _Type '**BruTile.Cache.FileCache**' in Assembly 'BruTile.Desktop, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' **is not marked as serializable**._  

Please can someone else verify?

Thanks

Tim

**Comment by FObermaier** [comment]
`BruTile` has a history of hiding properties, changing types or removing attributes.
Keeping the serialization working has always been a difficult path.

That is why I left the BruTile version for Net40 at v0.18.1. AFAIK serialization using `[Serializable]` does not work with netStandard. We'd have to come up with sth else.

**Comment by terribletim** [comment]
Thanks - seems like I'll need to revert for the time being.

> AFAIK serialization using [Serializable] does not work with netStandard. 

For reference (not of any help right at this moment) see [underlying bug in .Net Framework](https://github.com/dotnet/standard/issues/300#issuecomment-355066196) that has been [fixed](https://github.com/Microsoft/dotnet/blob/master/releases/net472/dotnet472-changes.md#bcl) in `.Net Framework 4.7.2`
