### ISSUE TITLE
DbaseReader and column name encoding

### ISSUE THREAD

**Issue by alsaleem00** [SharpMap/SharpMap#123]
The DbaseReader allows to set the encoding in case encoding is not recognized. However, I can only set encoding for record values.

I got several shp files with some column names encoded in widows-1256. I checked the code and it is fixed for UTF7.
Shouldn't the encoding of column names follow the encoding setting?

Thanks.

**Comment by FObermaier** [comment]
According to 
https://www.clicketyclick.dk/databases/xbase/format/dbf.html#DBF_STRUCT
field names have to be ASCII encoded.

As that is not an official source, we might consider being more lenient here.

**Comment by alsaleem00** [comment]
Yes. Indeed, the field names should be ASCII (UTF7). However, this is how we got them!
I used FastDBF to get them decoded, but it is better to do it in one package as we are using them with shapefile.

Speaking on official source, is development active on this project ? I meant that if new features are being developed.

Thanks.

**Comment by FObermaier** [comment]
After a period of suspense, we are working on a new release.

**Comment by alsaleem00** [comment]
Excellent.
