### ISSUE TITLE
how do create shpfile

### ISSUE THREAD

**Issue by bouyeijiang** [SharpMap/SharpMap#124]
how do create or export shpfile?

**Comment by terribletim** [comment]
Try [NetTopologySuite.IO.ShapeFile](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile) and see  [ShapeFileDataWriterTest](https://github.com/NetTopologySuite/NetTopologySuite.IO.ShapeFile/blob/master/NetTopologySuite.IO.ShapeFile.Test/ShapeFileDataWriterTest.cs) for samples

**Comment by bouyeijiang** [comment]
can support create memory shpfile?

**Comment by terribletim** [comment]
If you don’t require persistence, then Maybe you should be looking at [GeometryFeatureProvider](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Data/Providers/GeometryFeatureProvider.cs)

**Comment by bouyeijiang** [comment]
not yet support create the .prj file?

**Comment by bouyeijiang** [comment]
when  i define  enum type that about the  ShapefileDataWriter.GetHeader method have a bug

**Comment by FObermaier** [comment]
SharpMap has no support of creating a Shapefile. Use GDAL/OGR to do that.

**Comment by MarcosCobena** [comment]
Hi @FObermaier, we have recently used SharpMap for reading shapefiles and I came across this issue while looking for writting them. Could you please share a link or two regarding that GDAL/OGR you mentioned? Thank you in advance.
