### ISSUE TITLE
How to add a ColorBlend to a GdalRasterLayer?

### ISSUE THREAD

**Issue by semicloud** [SharpMap/SharpMap#125]
Hi, guys, I hava a problem when I using SharpMap to display a colorful GeoTiff file. My code as follows:

```C#
var mapBox = new MapBox { Dock = DockStyle.Fill };

var gdalRasterLayer = new GdalRasterLayer("raster_layer", @"Data/raster.tif")
 { ColorBlend = ColorBlend.BlueToRed };
 var vectorLayer = new VectorLayer("vector_layer", new ShapeFile(@"Data/vector.shp", false, false))
 { Style = new VectorStyle { Fill = Brushes.Transparent, Outline = Pens.Black, EnableOutline = true} };
mapBox.Map.Layers.Insert(0, gdalRasterLayer);
 mapBox.Map.Layers.Insert(1, vectorLayer);
 mapBox.Map.ZoomToExtents();
 mapBox.Refresh();
 this.Controls.Add(mapBox);
```

I have already set the `ColorBlend,` but it is not work, SharpMap still display the raster data as white and black.
![image](https://user-images.githubusercontent.com/13747974/49276021-23685500-f4b8-11e8-8c34-6d7e4bf9e6d7.png)

The demo project (VS 2017) and test data can be downloaded at:
https://pan.baidu.com/s/1jJXl2ESSlI98Tj3hatpNEQ

How do I change the raster's color using SharpMap ? Any suggestion is accepted. Thank you.

**Comment by FObermaier** [comment]
The `GdalRasterLayer.ColorBlend` property is only used when the displayed band is of type `GCI_Undefined`.
You need to wrap your GeoTiff to a [virtual raster](https://www.gdal.org/gdal_vrttut.html).

**Comment by semicloud** [comment]
Thank you for your wonderful help @FObermaier , I have already change the color blend using your advice. The main code as follows, may be someone need it.

            var mapBox = new MapBox {Dock = DockStyle.Fill};
            var driver = Gdal.GetDriverByName("VRT");
            // convert raster.tif to raster_demo.vrt
            var dataset = driver.CreateCopy(@"Data/raster_demo.vrt", Gdal.Open(@"Data/raster.tif", Access.GA_ReadOnly),
                0, null, null, null);
            // get the minimum and maximum value of the band, in order to generate color blend.
            double[] minMax = {0.0d, 0.0d};
            dataset.GetRasterBand(1).ComputeRasterMinMax(minMax, 0);
            Console.WriteLine("Min:{0}, Max:{1}", minMax[0], minMax[1]);
            // set color interpolation to GCI_Undefined
            dataset.GetRasterBand(1).SetColorInterpretation(ColorInterp.GCI_Undefined);
            // save to raster_demo.vrt
            dataset.FlushCache();
            // display the .vrt file
            if (File.Exists(@"Data/raster_demo.vrt"))
            {
                var gdalRasterLayer = new GdalRasterLayer("raster_layer", @"Data/raster_demo.vrt");
                gdalRasterLayer.ColorBlend = ColorBlend.BlueToGreen;
                gdalRasterLayer.ColorBlend = new ColorBlend(new[] {Color.Green, Color.Red},minMax.Select(Convert.ToSingle).ToArray());
               
                mapBox.Map.Layers.Add(gdalRasterLayer);
                mapBox.Map.ZoomToExtents();
                mapBox.Refresh();
                Controls.Add(mapBox);
            }
            else
            {
                MessageBox.Show("raster_demo.vrt not found!");
            }

the result as follows:
![image](https://user-images.githubusercontent.com/13747974/49362125-de8f2900-f718-11e8-90f7-4decd1c2218e.png)

Once again, thank you FObermaier.
