### ISSUE TITLE
Scalebar incorrect using OpenStreetMap as background

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#128]
i have this map with 1-km-boxes upon it. if i use OpenStreeMap (SRID 900913) as a background, the scalebars 1000m is ~half the size of a 1-km-box. i tried different srid's (found in wiki): 900913, 3857, 102113, 103100, 3785, 3587. same game.

![sharpmap_osm_scale_srid_900913](https://user-images.githubusercontent.com/10242264/49528917-39f61e00-f8b5-11e8-8d06-bfbbefb32481.png)

if the map's srid is 25832 (UTM32) the scalebar is correct.

![sharpmap_utm32_scale_srid_25832](https://user-images.githubusercontent.com/10242264/49529063-86d9f480-f8b5-11e8-9274-a687c4608618.png)

how do i get a correct scalebar with OpenStreetMap?

**Comment by terribletim** [comment]
Hi - thanks for pointing this out. For (Web) Mercator projection, size (distance) distorts as latitude increases from the Equator to the poles, where the scale becomes infinite. Refer to [Wikipedia](https://en.wikipedia.org/wiki/Mercator_projection#Scale_factor) for more info, and summary on [GisStackExchange](https://gis.stackexchange.com/questions/93332/calculating-distance-scale-factor-by-latitude-for-mercator). </br>
SharpMap scale bar renders using actual map units, so although this is technically correct it isn't of practical use for Web Mercator without applying a Cos Latitude correction. It is not possible (or convenient) to fudge the scale bar by applying the correction as a `CustomUnit`. Instead, I've been looking at adjusting ScaleBar private field `barUnitsPerPixel` by Cos Latitude for Web Mercator 3857 + variants. This is working well with several test grid and geog datasets from equator to 9,000,000mN (81deg) at 1,000,000m increments. </br>
Currently have other commitments but intend to tidy this up and submit a PR with samples in about a week.

**Comment by Lotto2** [comment]
Hi terribletim, i'll kiss your feet if you do;-)

**Comment by Lotto2** [comment]
A week seems a long time...;-)

**Comment by terribletim** [comment]
Aye. And a chaotic one at that. Unforeseen circumstances I'm sorry. Things almost back to normal and I haven't forgotten.

**Comment by FObermaier** [comment]
Closed with 1799eceaac9684adf3fdd4859a522cfbf93e67d9
