### ISSUE TITLE
VS2017 and SQL data

### ISSUE THREAD

**Issue by annemariedavid** [SharpMap/SharpMap#129]
Hi !

I have a project wich display SQL data. It works fine on VS2013 on a windows 7 machine. Since I have migrated my project to VS 2017 on windows 10, the SQL data are not showing on the map. Not red X, no  raised exceptions, no error messages, just no data displayed. I have added the microsoft.sqlserver.types, did everything I could regardless to the "Can anyone show me a step by step example on how to use Sharpmap to display MS SQL server" thread, whitout success. My OSM map shows properly. When I compile my app an run it on the citrix farm servers, it displays correctly. Looks like a locally have a problem, but what is it ?? Your help will be appreciated !!!

**Comment by annemariedavid** [comment]
Thanks for your response. So, yes, I can connect to SqlServer. My query works fine also. It returns a dataset contaning a geometry type. My provider is a sharpmap.data.providers.SqlServer2008 :

           Dim d As SharpMap.Data.Providers.SqlServer2008 = New SharpMap.Data.Providers.SqlServer2008(ConnStr, "DI", "SHAPE", "OBJECTID", SharpMap.Data.Providers.SqlServerSpatialObjectType.Geometry)
            d.DefinitionQuery = "DateDanger ='" & frmModelisation.opPP.Date2 & "'"

I use the nuGet shapmap's package.

**Comment by annemariedavid** [comment]
Ok, I have found out that it's the uniqueValuesTheme that cause the problem. SQL data is ok, but I cannot render it as I used to do in VS 2010 (same code but does not work in VS2017). Still searching !

Applying a uniqueValuesTheme on a shapefile works fine. As long as applying a customTheme on a vectorLayer. I really need your help because I don't know where to search from here !!

**Comment by annemariedavid** [comment]
Any idea, clue or hint ? I need it to work soon.. thanks !

**Comment by FObermaier** [comment]
Could you show us how you set up your `UniqueValuesTheme` and a (CSV)-sample of the attribute data? Maybe the data types don't match exactly.

**Comment by annemariedavid** [comment]
Yes, sure ! Thanks.. your help is appreciated. 
[UVR.txt](https://github.com/SharpMap/SharpMap/files/2828166/UVR.txt)

[DI.zip](https://github.com/SharpMap/SharpMap/files/2828165/DI.zip)
[DI.pdf](https://github.com/SharpMap/SharpMap/files/2828179/DI.pdf)

**Comment by FObermaier** [comment]
Maybe your issue is not databound at all. Have you tried to disable the `UniqueValuesTheme`?

```VB
Dim myLayer As SharpMap.Layers.VectorLayer = New SharpMap.Layers.VectorLayer("DI")
Dim ConnStr As String = "Server=sopfeu-esri-sql\esri_sde;Database=SIIF;User Id=siifsig;Password=sIIFsIG" 'Integrated Security=SSPI" 
Dim d As SharpMap.Data.Providers.SqlServer2008 = New SharpMap.Data.Providers.SqlServer2008(ConnStr, "DI", "SHAPE", "OBJECTID", SharpMap.Data.Providers.SqlServerSpatialObjectType.Geometry) With {
    .DefinitionQuery = "DateDanger ='" & frmModelisation.opPP.Date2 & "'"
}

myLayer.DataSource = d
myLayer.IsQueryEnabled = True

Dim ctf = New ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory()
Dim cf = New ProjNet.CoordinateSystems.CoordinateSystemFactory()
Dim epsg32198CS As String = "PROJCS[""NAD83 / Quebec Lambert"",GEOGCS[""NAD83"",DATUM[""North_American_Datum_1983"",SPHEROID[""GRS 1980"",6378137,298.257222101,AUTHORITY[""EPSG"",""7019""]],AUTHORITY[""EPSG"",""6269""]],PRIMEM[""Greenwich"",0,AUTHORITY[""EPSG"",""8901""]],UNIT[""degree"",0.01745329251994328,AUTHORITY[""EPSG"",""9122""]],AUTHORITY[""EPSG"",""4269""]],UNIT[""metre"",1,AUTHORITY[""EPSG"",""9001""]],PROJECTION[""Lambert_Conformal_Conic_2SP""],PARAMETER[""standard_parallel_1"",60],PARAMETER[""standard_parallel_2"",46],PARAMETER[""latitude_of_origin"",44],PARAMETER[""central_meridian"",-68.5],PARAMETER[""false_easting"",0],PARAMETER[""false_northing"",0],AUTHORITY[""EPSG"",""32198""],AXIS[""X"",EAST],AXIS[""Y"",NORTH]]"
Dim epsg32198 = cf.CreateFromWkt(epsg32198CS)

Dim csTgt = ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator
Dim ct = ctf.CreateFromCoordinateSystems(epsg32198, csTgt)

Dim D1 As SharpMap.Styles.VectorStyle = New SharpMap.Styles.VectorStyle()
D1.Fill = New SolidBrush(Color.LightBlue) : D1.Outline = Pens.Black : D1.EnableOutline = True ': D1.Outline.Width = 2
Dim D2 As SharpMap.Styles.VectorStyle = New SharpMap.Styles.VectorStyle()
D2.Fill = New SolidBrush(Color.LightGreen) : D2.Outline = Pens.Black : D2.EnableOutline = True ': D2.Outline.Width = 2
Dim D3 As SharpMap.Styles.VectorStyle = New SharpMap.Styles.VectorStyle()
D3.Fill = New SolidBrush(Color.Yellow) : D3.Outline = Pens.Black : D3.EnableOutline = True ': D3.Outline.Width = 2
Dim D4 As SharpMap.Styles.VectorStyle = New SharpMap.Styles.VectorStyle()
D4.Fill = New SolidBrush(Color.LightCoral) : D4.Outline = Pens.Black : D4.EnableOutline = True ': D4.Outline.Width = 2
Dim D5 As SharpMap.Styles.VectorStyle = New SharpMap.Styles.VectorStyle()
D5.Fill = New SolidBrush(Color.Firebrick) : D5.Outline = Pens.Black : D5.EnableOutline = True ': D4.Outline.Width = 2

Dim styles As Dictionary(Of Int32, SharpMap.Styles.IStyle) = New Dictionary(Of Int32, SharpMap.Styles.IStyle)
styles.Add(1, D1)
styles.Add(2, D2)
styles.Add(3, D3)
styles.Add(4, D4)
styles.Add(5, D5)
myLayer.Theme = New SharpMap.Rendering.Thematics.UniqueValuesTheme(Of Int32)("DANGER", styles, D1)

myLayer.SRID = 32198
myLayer.CoordinateTransformation = ct
'===============================================================
'REM THIS IS NEW:
myLayer.ReverseCoordinateTransformation = ctf.CreateFromCoordinateSystems(csTgt, epsg32198)
```

**Comment by annemariedavid** [comment]
Yes ! And the data display ok !
![capture](https://user-images.githubusercontent.com/45371761/52213179-58987700-285c-11e9-98c3-ea22500c3793.JPG)
