### ISSUE TITLE
compilation error: missing code

### ISSUE THREAD

**Issue by DGuidi** [SharpMap/SharpMap#132]
tried to build 1.0 branch and WinFormSamples project doesn't build, apparently because _SqlServerTipes_ folder wasn't added to the repo.

https://github.com/SharpMap/SharpMap/blob/9b400122265159fe9c98ca33cf14dcac735c5765/Examples/WinFormSamples/WinFormSamples.csproj#L186

**Comment by terribletim** [comment]
This folder and contents should have been added as part of NuGet package **Microsoft.SqlServer.Types** (v14.0.1016.290).

When I was working on PR #126 I ran into VS problem with packages not auto-refreshing, and had to manually Restore NuGet Packages for the solution.

**Comment by DGuidi** [comment]
yep. I've uninstalled and then installer microsoft.sqlserver.types package, and all is ok now. thans for super-fast support.

**Comment by DGuidi** [comment]
anyway, a little suggestion. add `loader.cs` and `readme.htm` files to .gitignore  

![Screenshot_61](https://user-images.githubusercontent.com/216627/56271752-866e2780-60f9-11e9-8d75-a416a07f6ce6.png)

**Comment by terribletim** [comment]
Update: 
1) The above info on `Microsoft.SqlServer.Types` has been superseded by PR #155 Please refer to [ReadMe.txt](https://github.com/SharpMap/SharpMap/tree/Branches/1.0/SharpMap.SqlServerSpatialObjects) for new info on required libraries to use SqlServer spatial types (ie geometry and geography).
2) NuGet package download still cropping up from time-to-time for different users, so this comment still valid:
> When I was working on PR #126 I ran into VS problem with packages not auto-refreshing, and had to manually Restore NuGet Packages for the solution.

Also, if some projects still refuse to compile, check out this post on [stackoverflow](https://stackoverflow.com/questions/52833741/your-project-does-not-reference-netframework-version-v4-6-2-framework-add-a) particularly with regard to deleting **bin** and **obj** folders.
