### ISSUE TITLE
how to lock the viewport by interface?

### ISSUE THREAD

**Issue by hongjiapeng** [SharpMap/SharpMap#133]
I want to transfer the interface of lock the viewport by interface,but I don't know how to do,do you know how to get it, I will be grateful.
![image](https://user-images.githubusercontent.com/26671281/56332972-f3022880-61c4-11e9-8544-bc27abf2a597.png)

**Comment by FObermaier** [comment]
On the `SharpMap.Map` you have to set the following properties:
* `MaximumZoom`
  The maximum value that `Map.Zoom` can take.
* `MinimumZoom`
  The minimum value that `Map.Zoom` can take.
* `MaximumExtents`
  The area that is allowed to be displayed on the map.
* `EnforceMaximumExtents`
  A flag indicating if the above value should be enforced.

**Comment by hongjiapeng** [comment]
okay,thank you,I have solved it.
