### ISSUE TITLE
WFS Provider not working at all?

### ISSUE THREAD

**Issue by bmomen** [SharpMap/SharpMap#138]
I cannot seem to get any geometry/bounding box information using the WFS Provider. I've tried all examples and mentions of this class online and still cannot get it to work. Anyone actually using this?

Edit: I'm using the default geoserver install and can successfully instantiate a WFS, however the extents and geometry are empty.

**Comment by bmomen** [comment]
The WFS Provider did not work for me since it was from the Nuget package, last updated 2014. After compiling the Github latest version it worked.

**Comment by mcbgis** [comment]
I compiled and got v1.2.0-alpha.470 which I updated to my project which is a console app.  Watching Fiddler, I see my app make the WFS call and GML 3.1.1 is returned but still no data on my map.  Any ideas?  Is there a way I can see the contents of the layer?
