### ISSUE TITLE
Extract MapViewport class from Map

### ISSUE THREAD

**Issue by FObermaier** [SharpMap/SharpMap#14]
`SharpMap.Map` is a pretty heavy class to pass around for rendering purposes.
Additionally a part of its properties is being computed upon access in performance critical sections of the rendering pipeline.

In order to faciliate and speed-up rendering I propose to extract the relevant portions of `SharpMap.Map` into a new `SharpMap.MapViewport` class. Please see attached file.

In order to benefit from this, the `SharpMap.Layers.ILayer.Render` interface has to change, too:

```
        /// <summary>
        /// Renders the layer
        /// </summary>
        /// <param name="g">Graphics object reference</param>
        /// <param name="map">Map which is rendered</param>
        [Obsolete("Use Render(Graphics, MapViewport)")]
        void Render(Graphics g, Map map);

        /// <summary>
        /// Renders the layer using the current viewport
        /// </summary>
        /// <param name="g">Graphics object reference</param>
        /// <param name="map">Map which is rendered</param>
        void Render(Graphics g, MapViewport  map);

```

[MapViewport.zip](https://github.com/SharpMap/SharpMap/files/128671/MapViewport.zip)

**Comment by am2222** [comment]
Does this is implimented yet in sharpmap 1.2?
