### ISSUE TITLE
developer documentation little fix

### ISSUE THREAD

**Issue by DGuidi** [SharpMap/SharpMap#140]
In [SqlServer Project readme](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.SqlServerSpatialObjects/ReadMe.txt) is stated that SQL Server 2008 CLR Types are needed: actually I've fixed my build in my PC installing SQL Server 2012 CLR Types too.

**Comment by terribletim** [comment]
I agree it's a bit confusing and can try to clarify now and then tidy up projects later. 

[SqlServer Project readme](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.SqlServerSpatialObjects/ReadMe.txt) **CLR Types** refers to `Microsoft.SqlServer.Types.dll`. 

`SharpMap.SqlServerSpatialObjects` project currently references `Microsoft.SqlServer.Types.dll` installed by SqlServer 2008 (ie v10), so yes, problems compiling if you don't have this installed. Likewise, for CLR spatial operations, also require `SqlServerSpatial.dll` (written in C++ and hence dependent on `msvcrXXX.dll`) - see Alastiar Aitchison's [book](https://www.apress.com/gp/book/9781430234913) for more info.

Getting the correct and compatible versions of these 3 libs can all be simplified by using NuGet `Microsoft.SqlServer.Types v14.0.1016.290` which is now actively maintained by Sql Server team:
- backwards compatible to SqlServer 2008 (including serialization change at 2012)
- supports both x86 and x64
- package includes compatible version of C++ runtime **msvcr120.dll**

The caveat is appropriate libraries (x86 or x64) must be manually loaded at runtime by client which would have been a breaking change. However, this could be done in `SharpMap.SqlServerSpatialObjects` using static **ctors** in several classes - a bit messy but would certainly make things a lot easier for everyone else without introducing breaking changes.

If no concerns then I can go ahead with this.
