### ISSUE TITLE
Can't get GeoAPI 1.7.5

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#144]
Can't rebuild Sharpmap solution, because can't update solution to GeoAPI 1.7.5  library  . 
The same question in  [https://github.com/NetTopologySuite/GeoAPI/issues/51]. 
Can't anybody get me full version of sharpmap solution with all needed packages ?

**Comment by terribletim** [comment]
I'm working with latest code base from Branches/1.0 and building successfully, so sounds like an issue with packages on your dev computer. Try restoring all packages on the solution prior to rebuild - for some reason VS doesn't always seem to detect and pull missing packages.

**Comment by aviabunin** [comment]
MaybeI don't have enough experience, but where I can find GeoAPI 1.7.5? Now there is no library for this on nuget. Could you put somewhere archive of all the necessary libraries?
I have try Install-Package GeoAPI -Version 1.7.5 , but with no success

**Comment by FObermaier** [comment]
> https://www.nuget.org/packages/GeoAPI/

Maybe you have limited your package source to some local nuget feed?
![pkgsrc](https://user-images.githubusercontent.com/2065346/61197734-bf0ca580-a6d6-11e9-9666-e0ee2aa4e6c1.PNG)

**Comment by aviabunin** [comment]
Thanks!

**Comment by aviabunin** [comment]
I still needed to correctly indicate package source

![image](https://user-images.githubusercontent.com/3097213/61205582-1cb1e980-a6f9-11e9-812b-7cae632f1d60.png)

**Comment by aviabunin** [comment]
Thank you very match! All works!
