### ISSUE TITLE
What BruTile version to use?

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#147]
In WinFormSamples is used BruTile version 2.0.1.0. I  and osm and google layers are shown correctly. When I have tried to use this version in my project  , got message 

> Error	CS0012	The type 'ITileSource' is defined in an assembly that is not referenced. You must add a reference to assembly 'BruTile, Version=0.18.1.0, Culture=neutral, PublicKeyToken=null'.	
>
When I replace reference on 0.18.1.0  I can see OSM and google layers (satellite images). How to do it correctly?

**Comment by FObermaier** [comment]
You need to update your TargetFramework to sth. higher than .Net40. Choose the same as in the WinFormSamples project.

**Comment by aviabunin** [comment]
Thank you very match!

**Comment by aviabunin** [comment]
I have updated my TargetFramework to 4.5 as in the WinFormSamples, but on the line
```
var googleLayer = new TileAsyncLayer(KnownTileSources.Create(KnownTileSource.BingHybridStaging),
                "TileLayer - Bing");
```
program step somewhere, not on the next line.

**Comment by aviabunin** [comment]
![bruTileErr](https://user-images.githubusercontent.com/3097213/61382965-6ac01c00-a8b6-11e9-99e3-f458468d7eff.jpg)

**Comment by aviabunin** [comment]
![bruTileErr1](https://user-images.githubusercontent.com/3097213/61383399-3f89fc80-a8b7-11e9-8eb1-4b2d32ff7c1b.jpg)

**Comment by terribletim** [comment]
There's a complete working sample in `Examples/WinFormSamples`. Run this project, and try the menu option **Shows Async Tile Layers [MapBox]**, and on the next form select **Google**. 

Also, `BruTile 0.18` has a dependency on `System.Data.SQLite.Core" version=1.0.109.1`. I think you have inadvertently got a later version. The SQLite owners recently de-listed this verion which means it doesn't appear in public lists. However, it's still there but you need to tweak Pacakge Manage settings to reveal delisted packaged.

**Comment by aviabunin** [comment]
Of course I am working with this sample. I repeated all reference from this project and can't  undestand what is the difference.  When I go to definition for TileAsyncLayer from Form2.cs in this project i go to SharpMapLayers(net40client), but in my project a go to SharpMap.Layers
![net40Client](https://user-images.githubusercontent.com/3097213/61459835-488dd300-a976-11e9-9605-fc0e3d55c0ab.jpg)
![TileAsyncLayer](https://user-images.githubusercontent.com/3097213/61459840-4af02d00-a976-11e9-8d28-9368828451a9.jpg)
?
P.S. Of course I get reference from right place

**Comment by aviabunin** [comment]
1. When connected to my solution those projects from SharpMap solution, that are connected in the example, then go to definition for TileAsyncLayer   is the same.
    
2. When  connected the Examples/WinFormSamples project to my  decision, it works correctly too.

**Comment by aviabunin** [comment]
After I copy app.config from winFormSample to my project,  OSM layer appeared. But when I am trying to switch to Google satellite Image - the error appear
 

> An error occured while fetching file

**Comment by aviabunin** [comment]
All works! 
Thank you very match!!!
