### ISSUE TITLE
device move

### ISSUE THREAD

**Issue by hongjiapeng** [SharpMap/SharpMap#148]
![image](https://user-images.githubusercontent.com/26671281/61437698-4cb6f200-a970-11e9-981a-1a53be9958df.png)
The program itself has a Center property that moves the device to the center of the screen. How do you move the device to one-third of the width of the screen? I will be very grateful,thank you!

**Comment by terribletim** [comment]
`Map.Center` and `Map.Envelope` give you the coordinates you will need in world units. 
Define a new `Envelope` at your desired location, then pass the envelope into `Map.ZoomToBox`

**Comment by hongjiapeng** [comment]
Is it necessary to define a Center,like property under the Map class, and then assign the Coordinate of the element to the Center? I'm sorry,I don't understand a bit.

**Comment by FObermaier** [comment]
If you do not want to change the width and height of your viewpoint area you only have to adjust the calculation of your `Map.Center` property.

As your offset (as I understand it) is 1/6th of the width  of the viewport to either side of the center you need to set `Map.Center` to
* `Map.Center = new Coordinate(devicePt.X + (1d/6d) * Map.Envelope.Width, Map.Envelope.Centre.Y)` or
* `Map.Center = new Coordinate(devicePt.X - (1d/6d) * Map.Envelope.Width, Map.Envelope.Centre.Y)`

**Comment by hongjiapeng** [comment]
> If you do not want to change the width and height of your viewpoint area you only have to adjust the calculation of your `Map.Center` property.
> 
> As your offset (as I understand it) is 1/6th of the width of the viewport to either side of the center you need to set `Map.Center` to
> 
> * `Map.Center = new Coordinate(devicePt.X + (1d/6d) * Map.Envelope.Width, Map.Envelope.Centre.Y)` or
> * `Map.Center = new Coordinate(devicePt.X - (1d/6d) * Map.Envelope.Width, Map.Envelope.Centre.Y)`

It's okay,thank you,this is a nice solution.
