### ISSUE TITLE
Attribute data is not supported by the GeometryProvider.

### ISSUE THREAD

**Issue by bluedayzz** [SharpMap/SharpMap#150]
Hello!!

![1](https://user-images.githubusercontent.com/3981160/62271193-fb7c2780-b472-11e9-826e-68c2a3683101.PNG)

I want to make a click event on the image("maker"). so I used the following sample code URL.
https://xaml.dev/post/2006/05/18/Using-NetTopologySuite-in-SharpMap

![2](https://user-images.githubusercontent.com/3981160/62271196-fc14be00-b472-11e9-8ce9-3fbd0c1b1a64.PNG)

but I face the exception.(SharpMap/Data/Providers/GeometryProvider.cs line 211)
What do I make a source code in function("OnExecuteIntersectionQuery", "ExecuteIntersectionQuery")?

>             //Convert click-point in image coordinates to world coordinates
>             Envelope ClickPnt = new Envelope(mapBox.Map.ImageToWorld(new System.Drawing.Point(e.X, e.Y)));
>             SharpMap.Data.FeatureDataSet ds = new SharpMap.Data.FeatureDataSet();
>             //Execute click-query on first layer in layers collection
>             (mapBox.Map.Layers[1] as SharpMap.Layers.VectorLayer).DataSource.ExecuteIntersectionQuery(ClickPnt, ds);
>             if (ds.Tables.Count > 0) //We have a result
>             {
>                 //Add clicked features to a new selection layer
>             }

> 
>         public override void ExecuteIntersectionQuery(Envelope box, FeatureDataSet ds)
>         {
>             throw new NotSupportedException("Attribute data is not supported by the GeometryProvider.");
>         }
> 
> 

Thanks.

SharpMap.UI ver 1.2.0.0 / Branches/1.0

**Comment by FObermaier** [comment]
Use `GeometryFeatureProvider`
