### ISSUE TITLE
WMS-Layer Https-Url, Error Could not download capabilities document from the server

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#156]
Hello,

i'm trying to load a WMS on the map. The URL is

https://www.wms.nrw.de/geobasis/wms_nw_dop

the error

"Error Could not download capabilities document from the server"

is returned.
It worked some time ago when the URL wasn't "Https" but "Http".

Any hints how to contact this WMS or where the problem ist?

**Comment by Lotto2** [comment]
Sorry, i forgot, here ist the code causing the error:

`Dim layWms As SharpMap.Layers.WmsLayer`
`layWms = New SharpMap.Layers.WmsLayer("DOP", "https://www.wms.nrw.de/geobasis/wms_nw_dop")`

**Comment by Lotto2** [comment]
The full error message (partly in german):

> Could not download capabilities document from the server. The server may not be available right now.Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden.

**Comment by Lotto2** [comment]
I traced the error in the DemoWinForm. The error occures in

SharpMap.Web.Wms

Client.cs

...
public XmlDocument GetRemoteXml()
...
WebResponse myResponse = myRequest.GetResponse();

**Comment by FObermaier** [comment]
Follow up in #163
