### ISSUE TITLE
Transform Coordiantes

### ISSUE THREAD

**Issue by TimThaler** [SharpMap/SharpMap#160]
Hi,
i want to display the the cooridnates of the cursor position in lat/long values. Right now i achive this this with the [SRIDReader](https://github.com/NetTopologySuite/ProjNet4GeoAPI/blob/develop/test/ProjNet.Tests/SRIDReader.cs) class.

 ```C#
private void MapMouseMove(Coordinate worldPos, MouseEventArgs imagePos){        
    CoordinateTransformationFactory ctfac = new CoordinateTransformationFactory();

     var toCS = GeographicCoordinateSystem.WGS84;
     var fromCS = SRIDReader.GetCSbyID(900913);

     CoordinateSystem cs = null;//GeoAPI.GeometryServiceProvider.Instance.  SridReader.GetCSbyID(4326);
     ICoordinateTransformation trans = ctfac.CreateFromCoordinateSystems(fromCS, toCS);

     double[] fromPoint = new double[] { worldPos.X, world};
     double[] toPoint = trans.MathTransform.Transform(fromPoint);

     label4.Text = $"{toPoint[0]}/{toPoint[1]}";
}
```
It seems terribly cumbersome. But i did not manage to make it work with these transformation methods because of conversion errors.
```C#
CoordinateSystemFactory csFac = new ProjNet.CoordinateSystems.CoordinateSystemFactory();
CoordinateTransformationFactory ctFac = new CoordinateTransformationFactory();

IGeographicCoordinateSystem wgs84 = csFac.CreateGeographicCoordinateSystem(
                "WGS 84", AngularUnit.Degrees, HorizontalDatum.WGS84, PrimeMeridian.Greenwich,
                new GeoAPI.CoordinateSystems.AxisInfo("north", GeoAPI.CoordinateSystems.AxisOrientationEnum.North), new GeoAPI.CoordinateSystems.AxisInfo("east", GeoAPI.CoordinateSystems.AxisOrientationEnum.East));


//Argument 5: cannot convert from 'GeoAPI.CoordinateSystems.AxisInfo' to  ProjNet.CoordinateSystems.AxisInfo'
//Argument 6: cannot convert from 'GeoAPI.CoordinateSystems.AxisInfo' to 'ProjNet.CoordinateSystems.AxisInfo´

List<ProjectionParameter> parameters = ....

IProjectedCoordinateSystem epsg900913 = csFac.CreateProjectedCoordinateSystem(
                      "Google Mercator", wgs84, projection, LinearUnit.Metre, new AxisInfo("East", AxisOrientationEnum.East),
                      new AxisInfo("North", AxisOrientationEnum.North));
```
When i use the CoordinatesSystems from ProjNet i get 
```
Cannot implicitly convert type 'ProjNet.CoordinateSystems.GeographicCoordinateSystem' to 'GeoAPI.CoordinateSystems.IGeographicCoordinateSystem'.
```

How do i have to change it to make it work?

The project is using these versions:

 - SharpMap 1.2.0
 - GeoAPI 1.7.5.0
 - ProjNet 2.0.0.0
 - NetTopologySuite 1.15.1.0

**Comment by FObermaier** [comment]
When you rely on GeoAPI (v1.7.5), you can't use ProjNet v2. ProjNet v2 does no longer have a dependency on GeoAPI. You need to use ProjNet v1.4.x

**Comment by FObermaier** [comment]
If the coordinate transformation is static, why don't you create it once and reuse it. Then the conversion is not cumbersome, all that remains is a call to `ct.Transform` and setting the label.

**Comment by TimThaler** [comment]
I put all this code in the event handler for simplicity (bad idea). Ok ill try to downgrade and use the factories directly since there are some inacurrancies in the transformation

**Comment by TimThaler** [comment]
Ok it everything worked when i switched to ProjNet 1.41
Thanks for the hint!
