### ISSUE TITLE
Custom Theme, FilterDelegate and LabelPositionDelegate

### ISSUE THREAD

**Issue by PABLOCORRO** [SharpMap/SharpMap#161]
When functions are used, the parameters are passed ByVal, could they change to ByRef?
it would be unnecessary to send large objects ByVal

_'Example: Create label layer with custom style
Dim lay As New SharpMap.Layers.LabelLayer("example")
lay.DataSource = New SharpMap.Data.Providers.GeometryFeatureProvider(fdt)
lay.Theme= New SharpMap.Rendering.Thematics.CustomTheme(AddressOf **custom_style**)

Public Function custom_style(**row As SharpMap.Data.FeatureDataRow**) As 
        SharpMap.Styles.LabelStyle
        Dim style As New SharpMap.Styles.LabelStyle
        style.ForeColor = Color.Magenta)
        Return style
End Function

_P.D. I speak Spanish, sorry for the translation_

**Comment by terribletim** [comment]
> unnecessary to send large objects ByVal

The object isn't "sent", only a pointer to the object. Maybe these pages by Jon Skeet will help:
[Parameter passing in C#](https://jonskeet.uk/csharp/parameters.html)
[References and Values](https://jonskeet.uk/csharp/references.html)
