### ISSUE TITLE
Does SharpMap/SharpMap.Layers.BruTile/Utilities/Wmts/ works?

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#17]
Hi,
In the dll version that I have downloaded this class does not excists..Do this works currently?where I can download last version of sharp map?It seems this version is not included in github..right?

**Comment by FObermaier** [comment]
In order to have fewer dependencies to the core project (SharpMap) I decided to split out the tile layers that depend on BruTile into a seperate project. This makes updating BruTile easier, too

You will have to compile the whole solution and use the self compiled assemblies.

**Comment by am2222** [comment]
it is very good news to hear because I have lots of problems with it..I will try to compile it and see what happens thanks

**Comment by KinchoKaoo** [comment]
What should I do to use an offline tile map?

**Comment by am2222** [comment]
@gorden1991  

This might help you

https://github.com/SharpMap/SharpMap/issues/79#issuecomment-375985573

To serve maps you can use `geoserver` or https://archive.codeplex.com/?p=geopbs
