### ISSUE TITLE
TileAsyncLayer, "OpenStreetMap", Remoteserver Error

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#170]
Hello,

lately tiles "...remoteserver...error..." are shown when opening OpenStreetMap as background layer.

Have i missed something?

Code:

```VB
Dim lyrOSM As New SharpMap.Layers.TileAsyncLayer(
    New BruTile.Web.OsmTileSource(), "OpenStreetMap")
lyrOSM.SRID = SMap.Map.SRID '900913
SMap.Map.BackgroundLayer.Add(lyrOSM)
```

**Comment by andrewyar** [comment]
I have the same problem. Error 429 'Too Many Requests'.

```C#
mapBox1.Map.BackgroundLayer.Add(new SharpMap.Layers.TileAsyncLayer(
    new BruTile.Web.OsmTileSource(), "OSM"));
mapBox1.Map.ZoomToExtents();
mapBox1.Refresh();
```

**Comment by DwewOlden** [comment]
I did some reading on this issue over the weekend. The issue itself can be solved (reportedly) by setting a different user agent in the the brutile request headers. I have not yet done any reading about how that translates to the brutile project.

Andrew

**Comment by Lotto2** [comment]
@DwewOlden 

Hello Andrew,

any details known about which agent to place in the header and where did you find these hints?

Greetz
Lothar

**Comment by DwewOlden** [comment]
This is a general one where they highlight why it’s happening (brutile)

https://github.com/openstreetmap/Nominatim/issues/466

And this is for osm brutile:
https://github.com/BruTile/BruTile/issues/103
https://github.com/Mapsui/Mapsui/issues/668

**Comment by FObermaier** [comment]
To avoid the `Error 429, Too many requests` a strategy of using a persistent cache and providing a user-agent should help resolve the issue. (_Beware, the code has not seen a compiler_)
```C#
var fileCacheDirectory = Directory.CreateDirectory(Path.Combine(
    Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "BruTile",
    knownTileSource.ToString()));

var asm = Assembly.GetEntryAssembly() ?? Assembly.GetExecutingAssembly();
var header = new ProductHeaderValue(productName, asm.GetName().Version.ToString());
var userAgent = new ProductInfoHeaderValue(header);

var p = KnownTileSources.Create(KnownTileSource.OpenStreetMap, 
    persistentCache:new FileCache(fileCacheDirectory.ToString() , "png", TimeSpan.FromDays(7)),
    userAgent:userAgent.ToString());
```

**Comment by Lotto2** [comment]
@FObermaier 
Hi Felix, your solution has to see a compiler in the BruTile-project before it can find its way into SharpMap?-)

**Comment by FObermaier** [comment]
I tried, it works with the current code in this repository.
Pre-Release packages can be [downloaded here](https://github.com/SharpMap/SharpMap/suites/413978617/artifacts/1270516)

**Comment by Lotto2** [comment]
Hi Felix, your pre-release, the latest Brutile-packages (2.1.2) and providing the user-agent worked. Will there be SharpMap 2.1 soon?
