### ISSUE TITLE
Is Sharpmap available for Linux

### ISSUE THREAD

**Issue by kinsung** [SharpMap/SharpMap#171]
Is Sharpmap available for Linux? How do I compile and use it on Linux? Are there any examples?

**Comment by FObermaier** [comment]
There is no release especially for linux but the core components should run. Some time ago, I tested SharpMap and SharpMap.UI successfully. There is a (probably outdated) example called [GtkFormSamples](https://github.com/SharpMap/SharpMap/tree/Branches/1.0/Examples/GtkFormSamples).
 
You can build parts of the main solution on linux using the "ReleaseLinux" configuration.

**Comment by kinsung** [comment]
Thanks！I got it.
