### ISSUE TITLE
WMS PSAD56 over Bing Maps

### ISSUE THREAD

**Issue by PABLOCORRO** [SharpMap/SharpMap#172]
Hi everyone!

### The following code works:
MapBox1.Map.SRID = 3785
_'Bing Maps (WGS84)_
Dim tile As New SharpMap.Layers.TileAsyncLayer(BruTile.Predefined.KnownTileSources.Create(BruTile.Predefined.KnownTileSource.BingAerial), "test")
tile.SRID = 3785
MapBox1.Map.BackgroundLayer.Add(tile)

_'WMS (WGS84)_
Dim wms As SharpMap.Layers.WmsLayer
wms = New SharpMap.Layers.WmsLayer("wms01", "  *** demostrative ***  ")
wms.SRID = 4326
wms.AddLayer("1")
MapBox1.Map.Layers.Add(wms)

### But if the wms layer has a PSAD56 origin (srid 4248), it doesn't work, is this a bug?

**Comment by FObermaier** [comment]
SharpMap does not reproject raster/image data. If you have a `Tile[Async]Layer` with a SRID of 3857, your WMS Layer should have the same spatial reference in order to match.

**Comment by PABLOCORRO** [comment]
The WMS of my interest supports srid 4326:
![image](https://user-images.githubusercontent.com/42850661/72814680-76104d80-3c33-11ea-8494-747df580fffb.png)

Then I try to set it in Sharpmap with:     wms.SRID = 4326
But it doesn't work either. Could it be that in the future Sharpmap can reproject raster/image data?

**Comment by PABLOCORRO** [comment]
Hi everyone
The problem that I observed is that the image was displaced several meters. I fixed this problem by changing the srid to 102100, according to getcapabilities this srid is not supported, but it really works:

wms.SRID = 102100
Thank you
