### ISSUE TITLE
Overlaying two WMTS layers

### ISSUE THREAD

**Issue by TimThaler** [SharpMap/SharpMap#173]
Hey everyone,
i was displaying a DOP map from a WMTS server serving raster-tiles with the 3857 SRS.
To do so a TileAsyncLayer was added to the Map. This was (is) working perfect.

Now it would be nice to add an overlay  showing the streets to this map.
To have the streets ontop of the map i changed it to a syncronous layer.
 
The problem is now that it takes very long to load for the first time when showing the whole map (which i would like to keep). After that 
it works ok.
When serving the tiles though async-layers the street layer is most of the time hidden behind the map layer, and is only displayed when dragging 
the map.
Can i somehow wait on a single tile from the map and then start downloading the corresponding overlay tile?
Or is there an more simple solution to serve (show) the map before the overlay

```


///// Form.cs
var layerMap = Provider.CreateLayer();
var layerOverlay = Provider.CreateOverlay();
_map.Map.BackgroundLayer.Add(layerMap);
_map.Map.Layers.Add(layerOverlay); 


////Provider.cs
public static TileLayer CreateLayer()   => new TileLayer(CreateTileSource(url: UrlDOP, "DOP"), "Tilelayer");
public static TileLayer CreateOverlay() => new TileLayer(CreateTileSource(url: UrlOverlay, "DOP OVERLAY"), "Tilelayer - Overlay");

internal static ITileSource CreateTileSource(string url, string layerName)
{
	var resp = WebRequest.Create(new Uri(url)).GetResponseAsync();
	ITileSource tileSource;

	using (var stream = resp.Result.GetResponseStream())
	{
		var tileSources = WmtsParser.Parse(stream);
		tileSource = tileSources.First(s => s.Name == layerName && s.Schema.Srs.Contains("3857"));
	}
	return tileSource;
}
```

**Comment by PABLOCORRO** [comment]
Hi TimThaler
Have you written code for the paint event?

**Comment by TimThaler** [comment]
Hello.
No i just discovered this event - in this context - now. It seems there are X-Y location information from the tiles to be rendered available, but not for which layer. 
I could think of  something like: waiting  until a certain DOP tile has been rendered and then render the corresponding overlay tile. If the overlay arrvies erlier, cache it until the DOP tile has been delivered and rendered. (?)

The overlay-tile format is png, not shape files/vector graphics.

**Comment by FObermaier** [comment]
@TimThaler, are you using latest released nuget packages or did you compile the solution yourself?
If you do the later, try setting the `MapBox.MapImageGeneratorFunction` to `MapBox.LayerListImageGenerator`.

`LayerListImageGenerator` is currently being worked on so you might experience other issues, but I hope this specific issue is addressed.

**Comment by TimThaler** [comment]
Hello @FObermaier,
yes, we are using the - 2 weeks old - compiled solution. 
I set the `MapBox.MapImageGeneratorFunction` as you suggested and it is working just fine. At certain Zoom level the overlay tiles arrive too early and then get overwritten by the  DOP tiles 
but it works perfect!

**Comment by TimThaler** [comment]
@FObermaier maybe i did not check yesterday carefully enough, but with
```
MapBox.MapImageGeneratorFunction = MapBox.LayerListImageGenerator;

TileAsyncLayer layerMap = Provider.CreateLayer();
TileAsyncLayer layerOverlay = Provider.CreateOverlay();
map.BackgroundLayer.Add(layerMap);
map.Layers.Add(layerOverlay);
map.MaximumExtents = dop.Envelope;
```

when  new tiles have to be collected the overlays are swallowed each time by the DOP images. 
Only then within scrolling of the zoom level the layers are in the right order.

When setting `layerMap .OnlyRedrawWhenComplete = true;` the layers get in the correct order but we then have to wait some time until the map is completely loaded which is not really conventient.
Is there another property i have to set?

**Comment by FObermaier** [comment]
Please try adding all layers to `map.Layers` and don't use `map.BackgroundLayer`

**Comment by TimThaler** [comment]
That is it. As you mentionend there are some other things happening, but the layers are rendered in the correct order

**Comment by FObermaier** [comment]
> As you mentionend there are some other things happening

@TimThaler, please let us know where we can improve `LayerListImageGenerator`. A known limitation is that the area to be updated is not correct, especially when using puntal data along with variable layers.

**Comment by TimThaler** [comment]
@FObermaier, right now i am working on smth else, but i ll get back to this as soon as i have some time.
