### ISSUE TITLE
increase loading speed of maps with sqlserver provider

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#18]
I have a simple question about loading speed. 
Does sqlserver provider loads whole map or it only loads features in view port ?
I mean is there any way to increase loading and showing features into map speed when we have a large number of features?

**Comment by FObermaier** [comment]
SqlServer only loads the geometries/features needed for the current map extent.
What is it that takes so long, the call for GetExtents() or getting the geometries/features

**Comment by am2222** [comment]
thanks for your great answer.
