### ISSUE TITLE
Wms with credential, maps isnt visible

### ISSUE THREAD

**Issue by canitez** [SharpMap/SharpMap#190]
Hi, 
Im using wms service with sharpmap. And wms service has credentials.As in the examples, I integrated my wms service. The map can only be displayed in certain coordinates. (36-42).I cannot view the map at the moment with the codes I wrote.I don't get an error, so I can't find where the problem is. First of all, is there any data in areas that I cannot see somewhere on the map? Can I see the data of the incoming pictures as an response? Or can you tell me what to do to solve this problem? thank you

I will not share information due to privacy. I can only share Capabilities data.
https://yadi.sk/d/EJrbbRgq0JqT7A

![code1](https://user-images.githubusercontent.com/8152086/87477013-11590d00-c630-11ea-9938-14e2caa40e2f.png)

![code2](https://user-images.githubusercontent.com/8152086/87477038-17e78480-c630-11ea-8786-452b4e91b99c.png)

**Comment by PABLOCORRO** [comment]
Hello!
Try using:
layWms.ForceOnlineResourceUrl(wmsUrl + "&username=xxx")
it worked for me!

**Comment by canitez** [comment]
thanks for your reply Pablocorro. I added the code you specified. I am seeing this error right now. 
![image](https://user-images.githubusercontent.com/8152086/87664009-3b641980-c76d-11ea-94a3-a1beef3989dc.png)

**Comment by FObermaier** [comment]
I assume this has to do with the transfrom you apply to the map. Does it work when you leave out setting `map.MapTransform`?
