### ISSUE TITLE
Sharp map in vb.net winforms not c#

### ISSUE THREAD

**Issue by markgapaz** [SharpMap/SharpMap#191]
hi can u translate all of this in vb.net or do u have existing please share me thanks alot.

**Comment by PABLOCORRO** [comment]
Hello!
I work with Sharpmap and Visual Basic in Windows Forms, but I recommend using WPF.
I recommend that you learn the basics of C # in order to understand the examples.

**Comment by markgapaz** [comment]
-->Thank u sir for your kindnest but I don’t have time to learn c# I just want to do simple things in .net for our office can u just give me simple codes or methods on some sample coding on sharpmap to vb.net sir or u just do c# sir?

**Comment by PABLOCORRO** [comment]
I don't program in C # either. You don't need C # to program in VB .NET and Sharpmap, but you do need to learn some C # stuff just to understand the examples, which is just what you want.

**Comment by markgapaz** [comment]
ok sir thanks alot if u dont have sample in vb.net and sharpmap

**Comment by PABLOCORRO** [comment]
All the examples are in C# but you can convert it to visual basic .net with some tool like
https://converter.telerik.com/
