### ISSUE TITLE
Can't compile sources 27.03.2020

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#192]
Hi,

just downloaded Branches/1.0 and tried to compile them with VS 2019. Compiling SharpMap.SqlServerSpatialObjects / SharpMap.Extensions throws an error

...\SharpMap-Branches-1.0\SharpMap.SqlServerSpatialObjects\SqlServerTypes\Loader.cs" not found

Directory SqlServerTypes does not exist in this path. Missing?

I heard rumors of a version SharpMap V1.2. Where are the sources to be found?

Greetings
Lotto2

**Comment by FObermaier** [comment]
Open console in the root folder of your SharpMap repository and invoke the following commands:
```
nuget restore SharpMap.Extensions/packages.config -OutputDirectory packages
nuget restore SharpMap.SqlServerSpatialObjects/packages.config -OutputDirectory packages
msbuild SharpMap.targets /t:Version
```

Then you should be all set to open the solution and build it.

**Comment by Lotto2** [comment]
Hi Felix,

1) nuget restore SharpMap.Extensions/packages.config -OutputDirectory packages
2) nuget restore SharpMap.SqlServerSpatialObjects/packages.config -OutputDirectory packages

After i downloaded nuget.exe from https://www.nuget.org/downloads, v5.6.0, and placed it in the root of my repository the commands 1) and 2) worked.

3) msbuild SharpMap.targets /t:Version

"Der Befehl "msbuild" ist entweder falsch geschrieben oder konnte nicht gefunden werden." -> msbuild not found

So i located a msbuild.exe in my system and tried

"C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" SharpMap.targets /t:Version

Resulted in --------------------------------------------------------------------

"Microsoft (R)-Buildmodul, Version 14.0.25420.1
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Der Buildvorgang wurde am 03.08.2020 13:01:34 gestartet.
Projekt "E:\Repositories\SharpMap_20200327\SharpMap-Branches-1.0\SharpMap.targets" auf Knoten "1", Version Ziel(e).
E:\Repositories\SharpMap_20200327\SharpMap-Branches-1.0\SharpMap.Common.props(1,1): error MSB4041: Der MSBuild-XML-Name
space muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-Element xmlns="http://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren Sie es in das MSBuild 2003-Format. [E:\Repositories\SharpMap_20200327\SharpMap-Branches-1.0\SharpMap.targets]
Die Erstellung des Projekts "E:\Repositories\SharpMap_20200327\SharpMapBranches-1.0\SharpMap.targets" ist abgeschlossen, Version Ziel(e) -- FEHLER.

Fehler beim Buildvorgang.

"E:\Repositories\SharpMap_20200327\SharpMap-Branches-1.0\SharpMap.targets" (Version Ziel) (1) ->
  E:\Repositories\SharpMap_20200327\SharpMap-Branches-1.0\SharpMap.Common.props(1,1): error MSB4041: Der MSBuild-XML-Na
mespace muss der Standard-XML-Namespace des Projekts sein. Wenn das Projekt im MSBuild 2003-Format erstellt wurde, fügen Sie dem <Project>-Element xmlns="http://schemas.microsoft.com/developer/msbuild/2003" hinzu. Wenn das Projekt im alten Format 1.0 oder 1.2 erstellt wurde, konvertieren Sie es in das MSBuild 2003-Format. [E:\Repositories\SharpMap_2020032
7\SharpMap-Branches-1.0\SharpMap.targets]

    0 Warnung(en)
    1 Fehler"

End result --------------------------------------------------------------------

Compiling SharpMap.SqlServerSpatialObjects / SharpMap.Extensions under VS still doesn't work.

Is it a wrong msbuild-version?

**Comment by FObermaier** [comment]
You need to start a developer console, one that gets installed with Visual Studio.
![grafik](https://user-images.githubusercontent.com/2065346/89178493-02f67500-d58e-11ea-8524-8c91a7fcc143.png)
