### ISSUE TITLE
BGCOLOR Parameter (WMS)

### ISSUE THREAD

**Issue by PABLOCORRO** [SharpMap/SharpMap#197]
Hi everyone

According to the WMS specification, the BGCOLOR parameter is used when TRANPARENT = False, but also in other cases regardless of the TRANSPARENT value :

![image](https://user-images.githubusercontent.com/42850661/96161450-e905d680-0edc-11eb-8923-e954327aed44.png)

Currently with TRANSPARENT = True (the source code ignores BGCOLOR):
![image](https://user-images.githubusercontent.com/42850661/96164541-f7ee8800-0ee0-11eb-8361-40b88010c682.png)

But if the source code is considered BGCOLOR regardless of the value of TRANSPARENT, when assigning green in BGCOLOR:
![image](https://user-images.githubusercontent.com/42850661/96164590-0a68c180-0ee1-11eb-9cb6-c0f9a2c59f06.png)

So I suggest you remove the condition that currently does not allow to use BGCOLOR when TRANSPARENT = True; the source code in **WmsLayer.cs** is this:

![image](https://user-images.githubusercontent.com/42850661/96165980-fde56880-0ee2-11eb-97de-3c9cb7872236.png)

Please I hope you consider my suggestion.
Thank's

**Comment by FObermaier** [comment]
Fixed with 254983ce6c3fc8d0a89b2368cdc6d992d26130e2
