### ISSUE TITLE
Wiki's sample not working

### ISSUE THREAD

**Issue by rusimao** [SharpMap/SharpMap#199]
Hello, I wanted to display .000 US chart but i couldn't becouse of exception "path does not lead to a file" 
So i tried to do something with wiki sample but im getting exception "cannot use geometryserviceprovider without an assigned igeometryservices"

The thing i want to do is to display a ENC after a button click.
Could you help me to go through? I even wanted to buy .shp enc bc i thought it has to work but not with me
```
 SharpMap.Layers.VectorLayer layer = new SharpMap.Layers.VectorLayer("States");
            layer.DataSource = new SharpMap.Data.Providers.ShapeFile("C:\\Users\\jakub\\Downloads\\states_ugl\\states_ugl.shp", true);
            layer.Style.Fill = new SolidBrush(Color.Transparent);
            layer.Style.Outline = new Pen(Color.Black);
            layer.Style.EnableOutline = true;
            layer.MaxVisible = 13000;
            
            mapBox1.Map.Layers.Add(layer);
                    mapBox1.Map.ZoomToExtents();
                    mapBox1.Refresh();
```

Edit: 
Okay, somehow i deleted an initialize component so sample is ok. 
But I wonder how to display a .000 file?

**Comment by FObermaier** [comment]
Most likely you will have to use the `GdalRasterLayer` or `OgrProvider` along with `VectorLayer`.
`GdalRasterLayer` and `OgrProvider` are part of the SharpMap.Extensions package
