### ISSUE TITLE
what is changed in sqlserver2008 provider in new versions?

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#20]
Hi,
In old versions of sqlserver2008 I could add a function as table name. but in the version here I can not, I only can add table names...I want to figure out what is chenged in new versions and how I can manege to use functions as table neme?
can some one helps me?
thank you

**Comment by FObermaier** [comment]
You can view the commit history here on github.
I assume that it has to do with security settings on the server.

**Comment by am2222** [comment]
thanks ..I find that the GetExtend method throws erros

**Comment by FObermaier** [comment]
I assume you have to change the `SqlServer2008.ExtentsMode` to `SqlServer2008ExtentsMode.QueryIndividualFeatures`

**Comment by am2222** [comment]
Yes,I changed it and it works fine because it calculates extend, I added new variable which take the main table name of related function and gets extend from spatial index
