### ISSUE TITLE
Can't connect to wfs server

### ISSUE THREAD

**Issue by SaschaDeWaal** [SharpMap/SharpMap#200]
Any clue why I can't connect to a wfs server? This is all I do, but with multiple servers, I always get the ApplicationException error. When I go to https://giswebservices.massgis.state.ma.us/geoserver/wfs?SERVICE=WFS&REQUEST=GetCapabilities it seems good.

**My Code**
`Client client = new Client("https://giswebservices.massgis.state.ma.us/geoserver/wfs");`

**Error**
```
ApplicationException: Could not convert the capabilities file into an XML document. Do you have illegal characters in the document.
SharpMap.Web.Wfs.Client.GetRemoteXml ()
```

**Comment by robhoney** [comment]
@SaschaDeWaal I wondered why you marked this as completed - I get this exact error and it's there in the latest code. The stream is being accessed by XmlTextReader after it has been closed (by virtue of the using command around the GetResponse).
