### ISSUE TITLE
How to save current viwing extend of map to set after loading a new map to mapbox

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#21]
Hi,
I want t keep current map view extent and then use it when a new Map object loads into mapbox,
Any way How Can I get current map viewing envelope?
thanks

**Comment by am2222** [comment]
I used the current method now..Does any better way exists

`          double zoom =-1;

```
        if (myMap != null && myMap.Zoom != null)
        {

            zoom = myMap.Zoom;
        }


        myMap = new SharpMap.Map();

        var env = parcellayer.Envelope;
        env.ExpandBy(4000);
        myMap.ZoomToBox(env);
        if (zoom!=-1)
        {

            myMap.Zoom = zoom;
        }
     `
```

**Comment by FObermaier** [comment]
This may look more compiicated but avoids changing Zoom value:

```
Envelope env = null;
Size siz;

if (myMap != null) {
    env = myMap.Envelope;
    siz = myMap.Size;
} else {
    siz = new Size(640, 480);
}

myMap = new SharpMap.Map(siz);
myMap.Layers.Add(parcelLayer);
if (env != null) {
    var dx = parcelLayer.Envelope.MinX - env.MinX;
    var dy = parcelLayer.Envelope.MinY - env.MinY;
    env.Translate(dx, dy);
} else {
    env = parcelLayer.Envelope;
    env.ExpandBy(4000);
}
myMap.ZoomToBox(env);
```

**Comment by am2222** [comment]
why are you using size? I think this make some problems if I use dock.fill option..doent it?

**Comment by FObermaier** [comment]
Changing the map Size implicitly forces a Refresh. Isn't it save to assume that the new map has the same size as the old map?

**Comment by am2222** [comment]
Can't I simply try Map.refresh()?
Yes In most cases the map size is fixed and it is dock.fill in an maximized form
