### ISSUE TITLE
Nuget: GDAL.Native web publish issue with MSBUILD 16.x, fix included

### ISSUE THREAD

**Issue by ALVIS-Software** [SharpMap/SharpMap#217]
Hi,
I am not sure if this is the right place for this issue.

I have found an issue with publishing my project with VS2019/MSBUILD 16 which uses the nuget packages:

- GDAL 2.4.4
- GDAL.Native 2.4.4

The required binaries under "bin\gdal" are missing in target publish folder.

The reason for this seems to be this condition within the GDAL.Native.targets file. The bold line does not exists in the official 2.4.4 package, I have added it to solve the problem. Please consider to add this version or to remove the condition completely.

  &lt;!--
  ******************************************************************************
  **                 GDAL Interop Library Publish Properties                  **
  **                       for Visual Studio 201x                             **
  ******************************************************************************
  --&gt;

  &lt;PropertyGroup Condition="'$(VisualStudioVersion)' == '' Or
                            '$(VisualStudioVersion)' == '10.0' Or
                            '$(VisualStudioVersion)' == '11.0' Or
                            '$(VisualStudioVersion)' == '12.0' Or
                            '$(VisualStudioVersion)' == '14.0' Or
                            '$(VisualStudioVersion)' == '15.0' **Or
                            '$(VisualStudioVersion)' == '16.0'**"&gt;
    &lt;PipelineCollectFilesPhaseDependsOn&gt;
      CollectGDALInteropFiles;
      $(PipelineCollectFilesPhaseDependsOn);
    &lt;/PipelineCollectFilesPhaseDependsOn&gt;
  &lt;/PropertyGroup&gt;
&lt;/Project&gt;

**Comment by FObermaier** [comment]
This package is no longer maintained by SharpMap, it is a part of the [gisinternals build system](/gisinternals/buildsystem) by @szekerest

**Comment by ALVIS-Software** [comment]
Thank you, I have raised the issue there.
You can close this one.
