### ISSUE TITLE
Unable to Render Tiled Background

### ISSUE THREAD

**Issue by jtsheedy** [SharpMap/SharpMap#219]
I have loaded the examples from the Winforms Examples and the Background maps work fine. However when I follow the instructions in the Wiki to load the tiles I get nothing back. I can load the shape file as can be seen howerver it does not load any of the tiles regardless of source.

My code is identical to the example on the wiki.

where an I going wrong.

![image](https://user-images.githubusercontent.com/12870518/117439342-a2380680-af2a-11eb-9370-1a8e24978bc4.png)

**Comment by PABLOCORRO** [comment]
can you show your code?

**Comment by jtsheedy** [comment]
`    
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;
using SharpMap.Data.Providers;
using SharpMap.Forms;
using SharpMap.Layers;
using SharpMap.Styles;
using BruTile.Predefined;
using GeoAPI.Geometries;
using GeoAPI.CoordinateSystems.Transformations;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using GeoAPI.CoordinateSystems;
using ProjNet.CoordinateSystems;
using ProjNet.CoordinateSystems.Transformations;
public frmMain()
        {
            InitializeComponent();
            SharpMap.Layers.VectorLayer vlay = new SharpMap.Layers.VectorLayer("States");
            vlay.DataSource = new ShapeFile(AppDomain.CurrentDomain.BaseDirectory + "\\data\\states_ugl.shp", true);

            //Create the style for Land
            SharpMap.Styles.VectorStyle landStyle = new SharpMap.Styles.VectorStyle();
            landStyle.Fill = new System.Drawing.SolidBrush(System.Drawing.Color.FromArgb(232, 232, 232));

            //Create the style for Water
            SharpMap.Styles.VectorStyle waterStyle = new SharpMap.Styles.VectorStyle();
            waterStyle.Fill = new System.Drawing.SolidBrush(System.Drawing.Color.FromArgb(198, 198, 255));

            //Create the theme items
            Dictionary<string, SharpMap.Styles.IStyle> styles = new Dictionary<string, SharpMap.Styles.IStyle>();
            styles.Add("land", landStyle);
            styles.Add("water", waterStyle);

            //Assign the theme
            vlay.Theme = new SharpMap.Rendering.Thematics.UniqueValuesTheme<string>("class", styles, landStyle);

            mbxMain.Map.Layers.Add(vlay);

            ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory ctFact = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory();
            vlay.CoordinateTransformation = ctFact.CreateFromCoordinateSystems(ProjNet.CoordinateSystems.GeographicCoordinateSystem.WGS84, ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator);
            vlay.ReverseCoordinateTransformation = ctFact.CreateFromCoordinateSystems(ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator, ProjNet.CoordinateSystems.GeographicCoordinateSystem.WGS84);

            mbxMain.Map.BackgroundLayer.Add(new TileAsyncLayer(KnownTileSources.Create(KnownTileSource.BingRoadsStaging, userAgent: DefaultUserAgent), "TileLayer"));

            mbxMain.Map.ZoomToExtents();
            mbxMain.Refresh();
            mbxMain.ActiveTool = SharpMap.Forms.MapBox.Tools.Pan;
`

**Comment by PABLOCORRO** [comment]
states_ugl.shp not found

**Comment by PABLOCORRO** [comment]
### This work ok:

public frmMain()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            ProjNet.CoordinateSystems.CoordinateSystemFactory csf = new ProjNet.CoordinateSystems.CoordinateSystemFactory();
            ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory ctf = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory();
            Session.Instance.SetCoordinateSystemServices(new SharpMap.CoordinateSystems.CoordinateSystemServices(csf, ctf, SharpMap.Converters.WellKnownText.SpatialReference.GetAllReferenceSystems()));

            SharpMap.Layers.VectorLayer vlay = new SharpMap.Layers.VectorLayer("States");
            SharpMap.Data.Providers.ShapeFile shapeds = new SharpMap.Data.Providers.ShapeFile(AppDomain.CurrentDomain.BaseDirectory + @"\data\states_ugl.shp");
            vlay.DataSource = shapeds;

            //Create the style for Land
            SharpMap.Styles.VectorStyle landStyle = new SharpMap.Styles.VectorStyle();
            landStyle.Fill = new System.Drawing.SolidBrush(System.Drawing.Color.FromArgb(232, 232, 232));

            //Create the style for Water
            SharpMap.Styles.VectorStyle waterStyle = new SharpMap.Styles.VectorStyle();
            waterStyle.Fill = new System.Drawing.SolidBrush(System.Drawing.Color.FromArgb(198, 198, 255));

            //Create the theme items
            Dictionary<string, SharpMap.Styles.IStyle> styles = new Dictionary<string, SharpMap.Styles.IStyle>();
            styles.Add("land", landStyle);
            styles.Add("water", waterStyle);

            //Assign the theme
            vlay.Theme = new SharpMap.Rendering.Thematics.UniqueValuesTheme<string>("class", styles, landStyle);

            mbxMain.Map.Layers.Add(vlay);

            GeoAPI.CoordinateSystems.ICoordinateSystem a = shapeds.CoordinateSystem;
            GeoAPI.CoordinateSystems.ICoordinateSystem b = (GeoAPI.CoordinateSystems.IProjectedCoordinateSystem)ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator;
            vlay.CoordinateTransformation = ctf.CreateFromCoordinateSystems(a, b);
            vlay.ReverseCoordinateTransformation = ctf.CreateFromCoordinateSystems(b, a);

            mbxMain.Map.ZoomToExtents();
            mbxMain.Map.BackgroundLayer.Add(new SharpMap.Layers.TileAsyncLayer(BruTile.Predefined.KnownTileSources.Create(BruTile.Predefined.KnownTileSource.BingRoadsStaging), "TileLayer"));
            mbxMain.Refresh();
        }

**Comment by jtsheedy** [comment]
I copied the code above and I am getting a null return on
` GeoAPI.CoordinateSystems.ICoordinateSystem a = shapeds.CoordinateSystem;`
when I change the file to one that covers the UK  and uses the 
`{PROJCS["ETRS89 / ETRS-LAEA", GEOGCS["ETRS89", DATUM["European_Terrestrial_Reference_System_1989", SPHEROID["GRS 1980", 6378137, 298.257222101, AUTHORITY["EPSG", "7019"]], AUTHORITY["EPSG", "6258"]], PRIMEM["Greenwich", 0, AUTHORITY["EPSG", "8901"]], UNIT["degree", 0.0174532925199433, AUTHORITY["EPSG", "9122"]], AUTHORITY["EPSG", "4258"]], UNIT["metre", 1, AUTHORITY["EPSG", "9001"]], PROJECTION["Lambert_Azimuthal_Equal_Area"], PARAMETER["latitude_of_center", 52], PARAMETER["longitude_of_center", 10], PARAMETER["false_easting", 4321000], PARAMETER["false_northing", 3210000], AUTHORITY["EPSG", "3035"]]}` 
coordinate system. I get the following error when running 
`vlay.CoordinateTransformation = ctf.CreateFromCoordinateSystems(a, b);`
![image](https://user-images.githubusercontent.com/12870518/117649174-1cfd5d80-b187-11eb-9bcf-edb51223e24b.png)

Shape file can be found here
https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/gis-files/great-britain-shapefile

**Comment by PABLOCORRO** [comment]
if the type of projection is not supported, it will not be possible

**Comment by jtsheedy** [comment]
> if the type of projection is not supported, it will not be possible

Yes I see that now. 

Still dont have an answer as to why the background maps are not loading based on the wiki example and the pasted example above.

**Comment by PABLOCORRO** [comment]
![image](https://user-images.githubusercontent.com/42850661/117691438-81b5b980-b181-11eb-9531-35ed1ca5fd9f.png)
_because WGS84 is not the corresponding coordinate system_

**Comment by jtsheedy** [comment]
OK getting back to the original point of my first post.

The Wiki Example is not working for me for some reason even though I have copied the code exactly on subsequent attempts the background map does not load just gives me the red X. does not matter what type of map I try to load.

The Wiki example map does not have a coordinate system associated with it.

Can someone show me why it is not working?

**Comment by PABLOCORRO** [comment]
It will not load any shapefile that has a Lambert_Azimuthal Equal Area projection.
The Wiki example refers only to WGS84.
Transform your shapefile to a compatible system (like WGS84), and Sharpmap will recognize it
