### ISSUE TITLE
MapBox does not fire mouse wheel to zoom in all parts

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#22]
Hi,
I have created a map box and added some layers into that map, every thing worked fine until suddenly I faced an strange problem,The zoom using mouse wheel does not work all the map box area,It only works ob corners and the center of map zoom using wheel dont work..Waht possible problems may cause this problem?
Here is an image of the areas that zoom works and where it does not work

https://i.imgsafe.org/0606841f7b.png

thanks for your help

**Comment by am2222** [comment]
An intresting thing that I noticed is that the map window is depended into my screen.I mean at bellow image zoom at the center of map does not work
http://i.imgsafe.org/07341bfd75.png

but when I move window to right side of screen zoom actives..

http://i.imgsafe.org/07344ef09a.png

what could make this happen?:(

**Comment by am2222** [comment]
I found the problem..When I use a map box in one form and run another form on top of that form while the previous mapox exists the area that the first map box covers mouse wheel does not work,I tried it by adding first map box to a splitcontainer and as I change the size of splitpanel mapbox in second form starts to work..how can I fix this?

**Comment by FObermaier** [comment]
Try
`MapBox.TakeFocusOnHover = true;`

**Comment by am2222** [comment]
> Try
> MapBox.TakeFocusOnHover = true;

I did the same but the problem exists..The area that map in first form occupies in new form mouse wheel does not work..

**Comment by FObermaier** [comment]
Can you set up a sample application for me to look at?

**Comment by am2222** [comment]
Hi,
sorry for my late answer
here is the download link
[https://www.mediafire.com/?aoj5lt2oi7m2vdl](https://www.mediafire.com/?aoj5lt2oi7m2vdl)

we have two forms.here there is two bugs,
1- when I load a layer to form 1 map layer in form 2 does not load any thing
2- when I load a layer in form 2..the area that map object in form 1 occupies mouse whel does not work..You can resize form1 and see that zoom using wheel works.

**Comment by am2222** [comment]
It seems this is a kind of bug

**Comment by am2222** [comment]
@FObermaier  Hi friend,
Can you test this problem and give me some hint why this happens?
Here is an example of this error

here is the download link
https://www.mediafire.com/?aoj5lt2oi7m2vdl

we have two forms.here there is two bugs,
1- when I load a layer to form 1 map layer in form 2 does not load any thing
2- when I load a layer in form 2..the area that map object in form 1 occupies mouse whel does not work..You can resize form1 and see that zoom using wheel works.

**Comment by Mangepange** [comment]
If you add the following code into App.xaml.cs of the WPFSamples application, its easy to see that wherever the two map-windows overlap, zoom does not work,

`public App()
    {
        var mw = new MainWindow();
        mw.Show();
    }`

I noticed that even if you close the underlying window, the area previously occupied STILL doesn't zoom. This lead me to check the private class MouseWheelGrabber in MapBox.cs which tells if the wheel should be active for the current window.

The current solution checks if the mouse position is contained inside of the map ClientRectangle, BUT this does not account for the case when another window with a map is on top of it. The MouseWheelGrabber class actually contains some commented code with an alternative solution, searching for the window currently below the mouse position. This code seems to work, but is not in use. Is there a reason for it not being used?

**Comment by FObermaier** [comment]
Good catch!
The code was removed because it relied on WinAPI calls. Should be fixed with 14ac1b14ffd080121e5a594453a99e0c80606a22
