### ISSUE TITLE
Destination array is not long enough to copy all the items in the collection. Check array index and length.

### ISSUE THREAD

**Issue by liugt34** [SharpMap/SharpMap#226]
In SharpMap.Data.Providers.DBaseReader.cs  at line 961

//case "System.Boolean":
case TypeCode.Boolean:
    var tempChar = BitConverter.ToChar(tmpBuffer, 0);
    return ((tempChar == 'T') || (tempChar == 't') || (tempChar == 'Y') || (tempChar == 'y'));

when i export a shapefile from PostGIS,  the DbaseField.Lenght == 1, but the BitConverter.ToChar must have 2 bits,
so i fix it by this way

`if(dbf.DataTypeCode == TypeCode.Boolean && dbf.Length == 1)
            {
                tmpBuffer = new byte[2];
            }`

**Comment by FObermaier** [comment]
A better fix would be to skip the `BitConverter.ToChar` part altogether:
```C#
case TypeCode.Boolean:
    return (tempBuffer[0] == 'T' || tempBuffer[0] == 't' ||
            tempBuffer[0] == 'Y) || tempBuffer[0] == 'y');
```

**Comment by liugt34** [comment]
> altogether
awsome, i got it
