### ISSUE TITLE
rendering a big rectangular with an X  in its center when I load a layer

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#23]
Hi,
I am using sharp map and on my pc with windows 10 every thing works fine. I have a sqlserver2008 provider which connects to a remote sql server and loads one layer and shows and every thing is OK,

But when I moved my app on windows 7 on two PCs my layer did not load and sharpmap only shows a big red rectangular with an X  in it. What can make this happen?

I know my sql connection works fine on all of PCs and I can work with them and also the envelope of my layer is right but Is does not render any thing,
What I need to fix this problem?

When does Red rectangle appears?
thanks

**Comment by DGuidi** [comment]
> big red rectangular with an X

this means an error, so you should see some exception in your code.

**Comment by am2222** [comment]
I can not see any thing in code, I works great on my laptop but when I move it to another pc it draws it

**Comment by DGuidi** [comment]
> when I move it to another pc it draws it

maybe you are some code like this?

```
try
{
// code that make some stuff
}
catch(Exception ex)
{
// no log here
}
```

try to take a look also to [EventViewer](http://www.howtogeek.com/school/using-windows-admin-tools-like-a-pro/lesson3/)

**Comment by FObermaier** [comment]
I think we can close this as it hase been resolved elsewhere
