### ISSUE TITLE
Drawing lat/lon coordinate grid (graticule)

### ISSUE THREAD

**Issue by dimales** [SharpMap/SharpMap#234]
I've created a reprojected map from a shapefile [(#232)](https://github.com/SharpMap/SharpMap/issues/232#issue-1206981092) and now trying to draw a coordinate grid (graticule) on top of that.

As suggested in [Graticule Map Decoration #154](https://github.com/SharpMap/SharpMap/pull/154#issue-490609880), I instantiate
`var grid = new SharpMap.Rendering.Decoration.Graticule.Graticule();`
and then add it to Decorations:
`map.Decorations.Add(grid);`

When running, I encounter _Unhandled Exception: OutOfMemoryException._
I know I'm doing something wrong when drawing graticule, but due to the lack of personal proficiency and experience I don't know what exactly is wrong. Any help, please?

**Comment by FObermaier** [comment]
You are not doing anything wrong, Graticule heavily relies on `ProjNet4GeoAPI`s API to work properly.

**Comment by dimales** [comment]
> You are not doing anything wrong, Graticule heavily relies on ProjNet4GeoAPIs API to work properly.

I see... If I got this right, since I have set up SharpMap to use DotSpatial library for reprojection **instead of** ProjNet4GeoAPI, I now cannot draw graticule with decorations? Or is there a setting, that would allow SharpMap create graticule decoration (which relies on ProjNet4GeoAPIs API) and only then use DotSpatial reprojection to reproject it and add to the map?

For now, I actually have found 3 ways to draw graticule:
    - Map decorations + SharpMap.Rendering.Decoration.Graticule.Graticule();
    - BuildGrid() method from [_SharpMap/Branches/0.9.5-DeltaShell/src/Common/SharpMap/Map/Map.cs](_SharpMap/Branches/0.9.5-DeltaShell/src/Common/SharpMap/Map/Map.cs) (which I don't yet know how to use);
    - Using separate shapefile, containing only graticule.
In my opinion, the best way would be with decorations which I would prefer to use, while the most clumsy way - separate shapefile.

**Comment by FObermaier** [comment]
In this particular case I'd go for the graticule Shapefile. It works best with the stereographic projection.

**Comment by dimales** [comment]
> In this particular case I'd go for the graticule Shapefile. It works best with the stereographic projection.

Yes, I think I'm going to use the graticule shapefile then, thank you.
So you think the reason is the type of projection and DotSpatial? Or maybe OutOfMemoryException raises due to the big envelope (I use `map.ZoomToBox(new GeoAPI.Geometries.Envelope(-5000000, 5000000, -5000000, 5000000));`)?

**Comment by FObermaier** [comment]
The graticule decoration relies on `IProjectedCoordinateSystem` and `IGeographicCoordinateSystem` to compute the graticule points. These interfaces are not implemented in `SharpMap.CoordinateSystems.DotSpatial` and thus the appropriate values cannot be computed correctly, which then leads to the `OutOfMemoryException`.
