### ISSUE TITLE
Heat Layer Help

### ISSUE THREAD

**Issue by Sgoyal2243** [SharpMap/SharpMap#24]
`Hi` Team,
I am using your HeatLayer Map , but i have following issues with this :-

1.How can i change the size of Heatpoint.?
2.can i create a polygon of different color using heat map?
3.How can i style the HeatLayer?
4 What is BlendOperation how can i implement this.?

Moto To Achieve:- I have different values on different point for one Source and i have multiple source in my file i just want to show those all different sources to map using heat layer . Can i achieve this by creating Polygon or by creating Points . Please help .
I have already gone through your example but i cant achieve this by your example .

Regards,
Sgoyal.

**Comment by FObermaier** [comment]
See [answer on codeplex](https://sharpmap.codeplex.com/discussions/656701#post1480176)
