### ISSUE TITLE
what does this error mean?Must declare a coordinate system services object

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#25]
Hi,
While I want to open an shapefile It gives me this error
`Must declare a coordinate system services object`
what does this error mean?how can I fixe it?

**Comment by am2222** [comment]
well this may help others 
`https://github.com/SharpMap/SharpMap/blob/faad193dc30c6724883f071632cbe683c84b45c0/Examples/ExampleCodeSnippets/ExampleCodeSession.cs`

**Comment by pdsrebelo** [comment]
Just a small correction, CoordinateSystemFactory constructor doesn't take arguments anymore.

**Comment by ab-tools** [comment]
Just wanted to try SharpMap, compiled the latest source code and ran the "DemoWinForm" project:
When I try to open any Shapefile I found (which work perfectly in other programs), it fails to open with the message "Must declare a coordinate system services object!" in the SharpMap demo project.

What's the reason for that?

As this seems to be the same as this issue, I didn't want to create a new one.

**Comment by am2222** [comment]
@ab-tools  just take a look at this file,

https://github.com/SharpMap/SharpMap/blob/faad193dc30c6724883f071632cbe683c84b45c0/Examples/ExampleCodeSnippets/ExampleCodeSession.cs

**Comment by ab-tools** [comment]
@am2222: Thanks for your reply!

But we decided to go with a custom ShapeFile rendering solution in the meantim.
