### ISSUE TITLE
Problems with placing an GeoTiff Image within a GDALRayer layer over a TileAsyncLayer

### ISSUE THREAD

**Issue by TimThaler** [SharpMap/SharpMap#259]
I try to place a geoTiff image onto a tileasync layer. But with this code only the async  layer will be rendered.
When i omitt the async layer i can see the geoTiff image instead. 

```

 var map = new SharpMap.Map();
 GdalRasterLayer layer = new SharpMap.Layers.GdalRasterLayer("GeoTiff", absPath + "utm.tiff");
 layer.ReprojectToCoordinateSystem(LayerTools.Wgs84toGoogleMercator.TargetCS);
 map.Layers.Add(layer);

 Layer asyncLayer = new TileAsyncLayer(...) { SRID = 3857 };
 map.Layers.Add(asyncLayer);

 System.Drawing.Drawing2D.Matrix mat = new System.Drawing.Drawing2D.Matrix();
 mat.RotateAt(0, map.WorldToImage(map.Center));
 map.MapTransform = mat;
 map.ZoomToExtents();


```
The layer uses a different coordiante system (EPSG 6326) as the underlying layer (which is basic web mercator).
The reprojection of the GeoTiff image works well. I see that the extent matches the real world extent.
This is the projection in WKT for the GeoTiff Image:

```
PROJCS[
"WGS 84 / UTM zone 33N",
GEOGCS["WGS 84",
DATUM["WGS_1984",
SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],
AUTHORITY["EPSG","6326"]],
PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],
UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],
AUTHORITY["EPSG","4326"]],
PROJECTION["Transverse_Mercator"],
PARAMETER["latitude_of_origin",0],
PARAMETER["central_meridian",15],
PARAMETER["scale_factor",0.9996],
PARAMETER["false_easting",500000],
PARAMETER["false_northing",0],
UNIT["metre",1,
AUTHORITY["EPSG","9001"]],
AXIS["Easting",EAST],
AXIS["Northing",NORTH],
AUTHORITY["EPSG","32633"]
]
```

**Comment by ALVIS-Software** [comment]
I hade experienced this bug as well, when I tried to reproject an UTM32N geotiff over a OSM background. There was a bug in GDALRasterLayer when the source image gets rendered.
There is a fix in our fork that could probably solve your issue as well:
https://github.com/ALVIS-Software/SharpMap/commit/919ae544338d9cba21e6009178dbdc117f1ffd83

**Comment by TimThaler** [comment]
Excellent! We are using the plain GdalRasterlayer class, adding your fix does not work but applying the example in your fork shows the geotiff images properly aligned with the unterlying layer. 
Taking your GdalRaster implementations needs some rewriting on our side, since for example underlying datatypes changed changed from GeoAPIGeometrics to ProjNetGeometrics.
But at least we know know it is doable - thats for sharing
