### ISSUE TITLE
IS there any sample how to edit geometries vertex by vertex?

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#26]
Hi,
I want to draw and edit geometries vertex by vertex..How can I do it?Can some one give me some examples?
I have already found this
`https://github.com/SharpMap/_SharpMap/blob/master/Branches/0.9.5-DeltaShell/src/Common/NetTopologySuite/Geometries/Utilities/GeometryEditor.cs`
but does not appear to works..or at least I dont know how to make it work
thanks

**Comment by FObermaier** [comment]
SharpMap has no vertex editing functionality.
