### ISSUE TITLE
System.InvalidOperationException: 'Must declare a coordinate system services object!'

### ISSUE THREAD

**Issue by azrellie** [SharpMap/SharpMap#264]
I have used this code before in other a couple other issues regarding this:
```
ProjNet.CoordinateSystems.CoordinateSystemFactory csf = new ProjNet.CoordinateSystems.CoordinateSystemFactory();
ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory ctf = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory();
Session.Instance.SetCoordinateSystemServices(new SharpMap.CoordinateSystems.CoordinateSystemServices(csf, ctf, SharpMap.Converters.WellKnownText.SpatialReference.GetAllReferenceSystems()));
```

But it does not work at all because the `ctf` and `csf` variables are using the `ProjNet` instead of `GeoAPI`. And an even bigger problem is that because the `GeoAPI` ones are interfaces, I am unable to create a new instance of them.

That saying, if I were to change it to this:
```
// doesn't work because its an interface
ProjNet.CoordinateSystems.CoordinateSystemFactory csf = new GeoAPI.CoordinateSystems.ICoordinateSystemFactory();

// doesn't work because its an interface
ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory ctf = new GeoAPI.CoordinateSystems.Transformations.ICoordinateTransformationFactory();

Session.Instance.SetCoordinateSystemServices(new SharpMap.CoordinateSystems.CoordinateSystemServices(csf, ctf, 
SharpMap.Converters.WellKnownText.SpatialReference.GetAllReferenceSystems()));
```
This would just bring up the problem of the fact that these are interfaces and not classes. And you can't make a new instance of an interface, which is a problem.

My project is on .NET Framework v4.8.1

**Comment by FObermaier** [comment]
See
https://github.com/SharpMap/SharpMap/blob/1d0f0efc56a9c1f0478eaa3f1306877dcbfff32e/Examples/WinFormSamples/Program.cs#L18-L32

**Comment by azrellie** [comment]
I have forgotten to mention that I also used that code, and the same exact problem had occurred (unable to convert ProjNet to GeoAPI).

**Comment by FObermaier** [comment]
In that case you need to use ProjNet4GeoApi v1.4.1.

**Comment by azrellie** [comment]
Working now, thanks.
