### ISSUE TITLE
MapBox throws exception when added to a form

### ISSUE THREAD

**Issue by jdwoodall** [SharpMap/SharpMap#27]
I have had the problem on and off for a while.  If I create a brand new blank project and add SharpMap and SharpMap.UI from Nuget along with all the other stuff it drags in, I get an error when I try to put a MapBox on the form.  It shows generally as something about SharpMap.UI already exists in the project.  Well, sure it does since it was just added by NuGet.

On an existing project, MapBox simply stopped functioning.  I had not updated the NuGet, it just stopped working and I can see it in the windows code, the MapBox is not visible in the designer window.  I tried to delete, but then I can not add a new one because I get the same error as above.

Obviously, there is a problem with MapBox and VS 2015.

Any ideas?

**Comment by am2222** [comment]
can you add control using code?

**Comment by FObermaier** [comment]
Old
