### ISSUE TITLE
set mouse position on map

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#29]
Hi,
I am working on an snapping tool.I need to set mouse position on map,But it does not work.I use this code

`private void snapToPoint(IPoint fdr)
        {
            if (fdr == null)
                return;
            var imagepoint = MapControl.Map.WorldToImage(fdr.Coordinate);
            snappingPoint = new System.Drawing.Point((int)Math.Round(imagepoint.X), (int)Math.Round(imagepoint.Y)); ;
            MapControl.BeginInvoke(new Action(() =>
            {
                var u = MapControl.PointToClient(snappingPoint);
                snappingPoint.X += u.X;
                snappingPoint.Y += u.Y;
                Cursor.Position = u;
            }));}
`
I have also set
`Cursor.Position = snappingPoint ;`
but none of them works..What can I do ?
thanks

**Comment by FObermaier** [comment]
You are aware that `Cursor.Position` is the position on your whole screen(s).
`Control.PointToClient` is taking a **screen** coordinate an translates it into a **client** coordinate, one that is relative to the top-left corner of the control that is calling this function.

What you have with `MapControl.Map.WorldToImage` is a **client** coordinate that you want to translate to a **screen** coordinate. Thus you need to set
```C#
private void snapToPoint(IPoint fdr)
{
    if (fdr == null)
        return;
    var imagepoint = MapControl.Map.WorldToImage(fdr.Coordinate);
    var snappingPoint = System.Drawing.Point.Truncate(imagePoint);
    var cursorPoint = MapControl.PointToScreen(snappingPoint);
    MapControl.BeginInvoke(new Action(() =>{ Cursor.Position = cursorPoint; }));
}
```
