### ISSUE TITLE
Highlight the selected geometry and enable feature selection on MapBox

### ISSUE THREAD

**Issue by rupakraj** [SharpMap/SharpMap#31]
Hello,

I am unable to select the feature on the map  and highlight the selected. geometry.

I have 2 layers Land, and its label. I wanted to make a tool to enable the click on map feature, highlight it with different background color and show the attribute on grid.

Edit: 

I have tried following 

```
 private void mapBox_MouseUp(GeoAPI.Geometries.Coordinate worldPos, MouseEventArgs imagePos)
        {
            var p = mapBox.Map.ImageToWorld(imagePos.Location);
            SharpMap.Data.FeatureDataSet ds = new SharpMap.Data.FeatureDataSet();

            foreach (var layer in mapImage.Map.Layers)
            {
                var queryLayer = layer as SharpMap.Layers.ICanQueryLayer;
                if (queryLayer != null)
                    queryLayer.ExecuteIntersectionQuery(parcelVectorLayer.Envelope, ds);
            }
            if (ds.Tables.Count > 0) dataGridView1.DataSource = ds.Tables[0];
        }
```

**Comment by am2222** [comment]
you don't need to convert worldPot into any kind of geometry, Just get its envelope (and meybe you have to grow it by a factor) and use it in ExecuteIntersectionQuery and it will return you the filltered geometries.

**Comment by rupakraj** [comment]
Thanks @am2222
