### ISSUE TITLE
Proper positioning of the Label

### ISSUE THREAD

**Issue by rupakraj** [SharpMap/SharpMap#32]
Hello,

I am rendering simple map data with different parcel, load, construction etc. The data has label associated with data set. Database is in PostgreSQL/PostGIS.
I used following to load Label

```

SharpMap.Layers.VectorLayer roadVectorLayer = ...
SharpMap.Layers.LabelLayer parcelLabelLayer = MapHelper.GetLabelLayer("LabelLayer", "parcelno");
parcelLabelLayer.DataSource = roadVectorLayer.DataSource;
parcelLabelLayer.SRID = roadVectorLayer.SRID;

// some styles

mapBox.Map.Layers.Add(roadVectorLayer);
mapBox.Map.Layers.Add(parcelLabelLayer);

```

Sample Output is as below
![capture](https://cloud.githubusercontent.com/assets/1549123/18424063/7b3af17c-78cb-11e6-98a9-81007d6e1370.PNG)

ParcelNo 9 is not placed properly.

How can I fix this kind of issue?

**Comment by FObermaier** [comment]
By default labels are placed on the center of the geometry's envelope. This is done for performance reasons.
You have to assign a `LabelPositionDelegate` function:

``` C#
parcelLabelLayer.LabelPositionDelegate = fdr => fdr.Geometry.InteriorPoint.Coordinate;
```
