### ISSUE TITLE
Problem visualizing with WMS layer on a background layer 

### ISSUE THREAD

**Issue by roccaab** [SharpMap/SharpMap#34]
I am using a mapBox control in which i load 
a layer (GoogleTileSource) and one from Wms service (WmsLayer).

Whilst the first one works I cannot visualize the wms layer on the background layer.
I tried whit various WMS services.

this is the code i use:

// GoogleTileSource
TileLayer googleLayer = new TileAsyncLayer(new GoogleTileSource(new GoogleRequest(GoogleMapType.GoogleMap), new MemoryCache<byte[]>(100, 1000)), "TileLayer - Google");
mapBox1.Map.BackgroundLayer.Add(googleLayer);
// Wms layer
WmsLayer layer = new WmsLayer("catastale", "http://.....");
...
mapBox1.Map.Layers.Add(layer);

Thanks!

**Comment by am2222** [comment]
whats your error or problem?I have tested this kind of function and they work great together

**Comment by roccaab** [comment]
I don't have neither compilation nor runtime problems.
The WMS layer seems to instantiate correctly.
In mapbox i can see the backround layer (google) that I can move and zoom into correctly, but I'm unable to see the overlap of any wms service with which I run a test.
I'm careful to modify the trasparent property to 'true'.
Maybe I don't correctly set the parameters of the wms request.
Could I have references of  a wms service that will surely work as an example?

**Comment by am2222** [comment]
@roccaab you know,It seems that you have some problems with wms parameters,Check Wmsexmamples project in source code,There is a working wms layer there
