### ISSUE TITLE
How to perform a reprojection on data

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#35]
Hi,
I have tested and found that reprojection of shape files have some problems, I can perform reprojection on some data but some of them has problems and make layer invisible or even make a map to draw a big red rectangle on it.
Is there a secure way to perform a shape file re projection on layers?

**Comment by FObermaier** [comment]
To help you with this, I'd have to See the Code you are using and an excerpt of the data (just geometry).

**Comment by am2222** [comment]
@FObermaier  sorry for my late answer. Here is my code.
```C#
 ShapeFile shapeFileData = new ShapeFile(connectionInfo);
 shapeFileLayer = new VectorLayer(layerName, shapeFileData);

if (shapeFileData.SRID  != GlobalVar.Google_webMercator_SRID)
{
    //Create zone UTM 32N projection
    IProjectedCoordinateSystem utmProj = LayerTools.CreateUtmProjection(32);
    //Create geographic coordinate system (lets just reuse the CS from the projection)
    IGeographicCoordinateSystem geoCS = utmProj.GeographicCoordinateSystem;

    ICoordinateSystem sourceCoordinateSystem = geoCS;
                    
    if (shapeFileData.CoordinateSystem != null)
    {
        sourceCoordinateSystem = shapeFileData.CoordinateSystem; 
    }

    if(sourceCoordinateSystem.Name!= "WGS_84_Pseudo_Mercator")
    {
        //Create transformation
        CoordinateTransformationFactory ctFac = new CoordinateTransformationFactory();
        ICoordinateTransformation transform = ctFac.CreateFromCoordinateSystems(sourceCoordinateSystem, LayerTools.epsg900913());

        //Apply transformation to a vectorlayer
        // shapeFileLayer.CoordinateTransformation = transform;
    }
}

//shapeFileLayer.SRID = GlobalVar.Google_webMercator_SRID;
```

If I uncomment `shapeFileLayer.CoordinateTransformation = transform;` part it show nothing for some shapes and for some others it draws a big red rectangular. Can you please give me some hint about fixing it? thanks

**Comment by FObermaier** [comment]
If it works for some Shapefiles than those probably have a different spatial reference system.
