### ISSUE TITLE
Problem with `IAsyncLayer`s and panning

### ISSUE THREAD

**Issue by FObermaier** [SharpMap/SharpMap#39]
Using `IAsyncLayer` as background layers exposes problems when continuously panning the map.
Arriving tiles are drawn at the wrong position.
[Discussion on Codeplex](https://sharpmap.codeplex.com/discussions/654669)

**Comment by FObermaier** [comment]
Taken from the discussion mentioned above:
>Please notice that while you are panning the map, if a tile arrives, mapbox seems to "come back" to draw the tile, moving the current map center position back and forward. 
I think this behaviour occurs also when connecting to a slow WMS server, not only with slow internet connection. You can check the Spanish land registry WMS server if you want to be annoyed by slow loading: http://ovc.catastro.meh.es/Cartografia/WMS/ServidorWMS.aspx?service=WMS&request=GetCapabilities 

> To deal with this kind of problems currently I set the OnlyRedrawWhenComplete property to true in TileAsyncLayer; no inmediate tile drawing but no panning problems.

**Comment by goldorak84** [comment]
Same problem here, even on a fast ASyncTileLayer mbTiles provider.
The problem occurs when zooming and panning when the tiles at a particular zoom level didn't finish to draw.
The result is so unconvenient for my users that I came back to use simple TileLayer. 
I hope someone finds the problem.

**Comment by PachisPachis** [comment]
Hi Felix

I'm still using Sharpmap for a street lighting GIS, no greater tool found. 

Our lighting inventory is getting bigger and bigger so it would be great to be able to turn on OnlyRedrawWhenComplete without breaking the background tile layer.

I tried by myself to fix it but exceeds my skills.

Regards.

**Comment by FObermaier** [comment]
Need to investigate

**Comment by FObermaier** [comment]
As far as I can tell, this is fixed with f178d6572412cd5dba340a0cf6fa10d0f1da435e

**Comment by PachisPachis** [comment]
Thanks, I will let you know how it works when updating the component in the
application
