### ISSUE TITLE
Style based on feature data returns nothing with null data

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#42]
Hi,
I have faced a problem.When I want to style a vector feature set base on its data column if they have null values in that column nothing shows. I think there must be some rules to deal with null values. Is there any way to fix it?
thanks

**Comment by FObermaier** [comment]
Which theme are you talking about?

**Comment by am2222** [comment]
simple theme base on feature data.this is a  piece of code which return nothing if we have null values in "PopDens" 

//Create theme using a population density from 0 (min) to 400 (max)
myVectorLayer.Theme = new SharpMap.Rendering.Thematics.GradientTheme("PopDens", 0, 400, min, max);

**Comment by FObermaier** [comment]
The VectorLayer explicitly handles `ITheme.GetStyle(fdr) == null` so I'm hesitant to changing this behavior.
You can wrap your gradient theme in a `CustomTheme`, that returns e.g. standard style in case the gradient theme returns `null`

**Comment by FObermaier** [comment]
There may be applications that rely on this behavior and it's not impossible to get around this.

**Comment by am2222** [comment]
thanks for your help
