### ISSUE TITLE
Any example of linear layer lable

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#44]
Hi,
I can easily set lable for polygons but when I use this code for lines or point it shows nothing. what can cause this problem?

here is my code
```C#
public static LabelLayer CreateLabelLayer(VectorLayer originalLayer, string labelColumnName) {

    SharpMap.Layers.LabelLayer ll = 
        new SharpMap.Layers.LabelLayer(originalLayer.LayerName + ":Labels");
    ll.DataSource = originalLayer.DataSource;
    ll.LabelColumn = labelColumnName;
    ll.Style.CollisionDetection = true;
    ll.Style.CollisionBuffer = new SizeF(10F, 10F);
    ll.LabelFilter = 
        SharpMap.Rendering.LabelCollisionDetection.ThoroughCollisionDetection;
    ll.Style.Offset = new PointF(0, -10F);
    ll.MultipartGeometryBehaviour = 
        SharpMap.Layers.LabelLayer.MultipartGeometryBehaviourEnum.CommonCenter;
    ll.Style.Font = new Font(FontFamily.GenericSansSerif, 14);
    ll.MaxVisible = originalLayer.MaxVisible;
    ll.MinVisible = originalLayer.MinVisible;
    ll.Style.Halo = new Pen(Color.White, 2);
    ll.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality;
    ll.CoordinateTransformation = originalLayer.CoordinateTransformation;

    return labelLayer;
}
```

**Comment by FObermaier** [comment]
Try to 
* set `ll.Style.IgnoreLength = true;`
* omit `ll.Style.MinVisible` and `ll.Style.Maxvisible` or check if `ll.Style.VisibilityUnits` fits the values assgigned to Min-/MaxVisible

If that fails provide a small sample shapefile along with the values of the variables used in the sample code above (`labelColumnName`, `originalLayer.MaxVisible`, `originalLayer.MaxVisible`)

**Comment by FObermaier** [comment]
Is this resolved?

**Comment by am2222** [comment]
Hi dear @FObermaier ,
Sorry for my late answer, I am currently does not have any access to my developing machine so I could not check it, I'll share the results soon. Thanks
