### ISSUE TITLE
Simple example using local image files

### ISSUE THREAD

**Issue by reubengann** [SharpMap/SharpMap#46]
Sorry, I couldn't find this in the documentation. I want to load a map from local files (jpg, for instance) in a folder structure. It looks like the expectation is that folder 0 will have 0.jpg, folder 1 will have two subfolders, 0 and 1, with each having files 0.jpg and 1.jpg in them, etc. So I have that structure, and I try to show them using a MapBox component from SharpMap.UI:

```
private void Form1_Load(object sender, EventArgs e)
{
    string appdir = Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
    FileCache fc = new FileCache(appdir + "\\Tiles", "jpg");
    SharpMap.Map map = mapBox1.Map;
    FileTileProvider FTP = new FileTileProvider(fc);
    TileSchema TS = new TileSchema();
    Resolution R = new Resolution();
    R.Id = "1";
    TS.Resolutions.Add(R);
    TileSource tileSource = new TileSource(FTP, TS);            
    map.Layers.Add(new TileLayer(tileSource, "1"));            
    mapBox1.Refresh();
}
```

I'm reasonably sure that the FileCache and FileTileProviders are working correctly, because if, for instance, I insert
```
byte[] foo = fc.Find(new TileIndex(0, 0, 1)); //works
```
the variable foo holds 16304 bytes (the size of my 1\0\0.jpg file). Likewise, if I insert
```
TileInfo TI = new TileInfo();
TI.Index = new TileIndex(0, 0, 1);
byte[] foo = FTP.GetTile(TI); //works
```
foo once again holds 16304 bytes. However, in debug if I look at the mapBox1.Map object, inspection says that in Layer 0 _bitmaps has zero elements, and nothing displays in the MapBox.

Kinda tearing my hair out here. Could someone point me in the right direction? I'm using the latest SharpMap and SharpMap.UI from NuGet in VS 2015.

**Comment by FObermaier** [comment]
Your `TileSchema` is not set up correctly I suppose.

**Comment by reubengann** [comment]
I have tried filling in the TileSchema so that it validates, though I'm adding things more or less at random

```
TileSchema schema = new TileSchema
{
    Name = "1",
    OriginX = 0,
    OriginY = 0,
    Extent = new Extent(-200, -200, 200, 200),
    Format = "png",
    Srs = "EPSG:900913",
    Width = 400,
    Height = 400
};
```
but I see no difference. How should the TileSchema be set?
