### ISSUE TITLE
.ecw file becomes invisible, if you make the background pixels invisible 

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#48]
Dear Gurus! 
I took BlueMarble 40.ecw file , loaded it in GlobalMapper, reprojected it to the EPSG 3857 (wgs84 Mercator) and saved with setting parameter "Set background pixels invisible".  After that I see it in arcmap and do not see in sharpmap project. [This is an example of .ecw file](https://cloud.mail.ru/public/GSXy/Eyk2an7Uw)

**Comment by FObermaier** [comment]
The problem is, that the ecw does not contain information about how to interpret the individual bands, they are all marked as being undefined.

I don't know if there is a way to mark each band to their respective band values using GlobalMapper.

**Comment by aviabunin** [comment]
But arcmap somehow do this...
