### ISSUE TITLE
GeoTransform does not calculate inversion matrix

### ISSUE THREAD

**Issue by becio** [SharpMap/SharpMap#49]
Under some circumstances, I have reproduced this with a large .ecw file, the GetTransform class does not calculate the inverse transformation needed to render the layer.

This is because the delta resulting from the matrix is less than epsilon value fixed in code, that is 1e-12, see the method ComputeInverse() from the GeoTransform class.

I do not know why it has been choosen this value and not another one, for sure the problem goes away, and the raster is rendered, if we remove this threshold from that method.

We could also solve it by lowering the value of Epsilon.

**Comment by FObermaier** [comment]
The intent is to avoid DivisionByZero exceptions. I'm not sure, but maybe it was introduced based on some ReSharper suggestion. @becio feel free to change it accordingly.

**Comment by becio** [comment]
Changed the value of Epsilon to Double.Epsilon
