### ISSUE TITLE
Render map with layers have different SRIDs?

### ISSUE THREAD

**Issue by nhvu1988** [SharpMap/SharpMap#51]
I have a problem when rendering map with layers have different SRID.
For example, I initialize a map with SRID 25832 since I would like to use 25832 as a default SRID when changing something such as Center or Envelope. Also when getting drawing coordinates on map.

    var map = new Map {
        SRID = 25832
    };

For background layer, I use OSM (SRID 3857)

    // OSM SRID 3857
    var osmLayer = new TileAsyncLayer(BruTile.Predefined.KnownTileSources.Create(), "OSM");
    map.BackgroundLayer.Add(osmLayer);

And WMS layer that has SRID 25832 

    // SRID 25832 
    var wmsLayer = new WmsLayer("wmslayer", "...");
    map.Layers.Add(wmsLayer);

The issue is background map doesn't render to correct location when I set new center for map since the background layer has a different SRID with map and WMS layer, I think

    // coordinate in 25832
    map.Center = new Coordinate(475666, 6350463);
    map.Refresh();

Anyone know how I can make them work together. Thanks :)

**Comment by FObermaier** [comment]
TileAsyncLayer does not perform any reprojection.
You have to transform your vector layers to the projection of your tiles.
