### ISSUE TITLE
Programming Practices with Locks/SyncRoot for Map / VariableLayerCollection / VectorLayer / GeometryProvider / GeometryFeatureProvider

### ISSUE THREAD

**Issue by terribletim** [SharpMap/SharpMap#53]
I’m relatively new to GitHub and would like feedback on a couple of points before working on any updates and issuing pull request. Links are provided to relevant code.

**Background:** 
I have been reviewing locks in above classes in relation to dynamic layers in VariableLayerCollection. I am managing dynamic layers and their geometries on a separate thread, and one or more of the dynamic layers may be used in more than one map (eg main map and overview, or map for mobile object X and another map for mobile object Y). Layers associated with single mobile object use GeometryProvider datasource, or multiple mobile objects may be shown in a single layer with GeometryFeatureProvider datasource using heading column to rotate symbol appropriately for each mobile object.

I note that locks are used in VectorLayer and GeometryFeatureProvider, but not in GeometryProvider. I think I understand the intent of the locks but I am unsure on the effectiveness of some of them as described below. 

[GeometryFeatureProvider](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Data/Providers/GeometryFeatureProvider.cs)
Underlying DataTable is safe for multi-threaded read operations, but not write.

Two locking objects (_featuresLock and _feautures ) are used but neither of these locks actually do anything to prevent modification to the rows in underlying FeatureDataTable. Would selective use of DataTable.Rows.SyncRoot be more effective? 

[GeometryProvider](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Data/Providers/GeometryProvider.cs)
Currently no locks at all. Locking on ICollection.SyncRoot would provide thread-safety, allowing updating of geometries and rendering to be appropriately synchronized (which is my main concern at the moment). 

However, this raises another issue of potentially slowing rendering of entire map as all layers are processed sequentially. **gennadiy_d_cp** has proposed map.cs renders layers as parallel tasks [see separate branch](https://github.com/SharpMap/_SharpMap/blob/master/Branches/0.9.5-DeltaShell/src/Common/SharpMap/Map/Map.cs#L356) or perhaps modify to limit tasks to (predefined) groups of layers.

**VectorLayer**
Locks are used to restore datasource to open/closed state:
    [public override Envelope Envelope](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L139)
    [protected void RenderInternal(Graphics g, MapViewport map, Envelope envelope, ITheme theme)](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L239)

The same locking object is also used when open/closing datasource, but without restoring open/closed state:
    [protected void RenderInternal(Graphics g, MapViewport map, Envelope envelope, ITheme theme)](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L239)
    [public void ExecuteIntersectionQuery(Envelope box, FeatureDataSet ds)](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L550)
    [public void ExecuteIntersectionQuery(IGeometry geometry, FeatureDataSet ds)](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L573)

Is there a reason for this, or should the latter be updated to restore open/closed state?

[VariableLayerCollection](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VariableLayerCollection.cs)
Public Static methods cause VariableLayerCollections to render simultaneously across all MapBox / MapImage instances. While this may be desirable in some cases, in other cases it makes sense for maps to be entirely independent as VariableLayerCollection may have different contents and different refresh rates may be appropriate for different maps.

Should both cases be supported? Or should public static members/methods be changed to instance level members/methods?

Similarly, am I correct in understanding the internal touchTest is used to temporarily delay raising redraw event if another user operation is in progress (eg pan)? I previously submitted a pull request to try and resolve some redraw issues here, but I think this should be cancelled as it is only a partial fix and doesn’t address above points.

**Finally**
Thanks to all involved in SharpMap. I continue to learn as I work through the code. I’m willing to contribute but still learning the finer arts on acceptable coding standards (eg use of inline comments etc). Any suggestions / constructive criticism will be well received.

**Comment by becio** [comment]
**GeometryFeatureProvider**: you are right, the locks are wrong, __featuresLock_ must be removed, the correct way to go is using _DataRowCollection.SyncRoot_ as you suggest. Probably this lock has never been really useful.

**GeometryProvider**: layers sometimes are processed parallelly, see the use of the _LayerCollectionRenderer_ class. Maybe a read/write lock can fit. The goal is to not add any further noticeable overhead to support a rare need.

**VectorLayer**: the open state of the provider is checked only inside those methods that are supposed to be called internally from other methods where the state is already open. I think it is better to always restore the state.

**VariableLayerCollection**: this class is **very** limited, there should be a single variable layer collection per map, I did some attempts in this direction in the past but I have not committed anything yet because it was inside an attempt to refactor the rendering of the UI control.

If you have some code to post go ahead and I will do some tests.

**Comment by terribletim** [comment]
Thanks for prompt response and offering to do some tests. I hope to have code ready within 2 weeks. How do I post - submit a pull request?

**Comment by becio** [comment]
You should fork the project on GitHub: https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by terribletim** [comment]
@becio I have submitted a pull request for the above (excepting Variable Layer Collection). I have also performed some tests on data from shapefile dataprovider.

Apologies for delay.... I injured my hand requiring stiches which put me out of action for a while.

**Comment by terribletim** [comment]
@becio I have also updated VariableLayerCollection as a 2nd commit (I see this has been included in my initial pull request).

Following on from above discussion on VariableLayerCollection, I'm assuming static members were originally used to avoid race condition described in [MSDN Timer.Stop](https://msdn.microsoft.com/en-us/library/system.timers.timer.stop(v=vs.110).aspx). 

Static methods are fine for a single map, but cause issues for multiple maps, so I have replaced static members/methods with instance members/methods while still respecting single variable layer collection per map. This is a minor breaking change for apps calling static method VariableLayerCollection.TouchTimer (easily resolved as all cases have reference to map so can replace with map.VariableLayers.TouchTimer). 

I have kept potential race condition in mind (which would only be an issue during map.Dispose) and think I have handled this correctly.

I have also fixed previously mentioned bug in TouchTimer causing delays and double refreshes, and have successfully tested on **FormMovingObjectOverTileLayer.cs** and **FormMapBox.cs**.

**Comment by terribletim** [comment]
@becio have found and fixed a problem in my in update for GeometryFeatureProvider, and included in pull request.

**Comment by terribletim** [comment]
@becio another commit has been added to the pull request following extensive use of `GeometryFeatureProvider`.

Re commit on **VariableLayerCollection**... question I should have asked originally is whether it is desirable for `TouchTimer` to refresh layers immediately (and queue any further refreshes for 0.5 secs), or to queue requests for 0.5 seconds then refresh. My changes support the former, but belatedly realizing original code may have intended the latter? 

Also, if my changes to Static methods in **VariableLayerCollection** are an issue with merging pull request, then I'm happy to revert, but if possible would like to retain the **TouchTimer** changes.
