### ISSUE TITLE
GdalRasterLayer Open file with chinese-character fileName Occur Excepton 

### ISSUE THREAD

**Issue by bowen2018** [SharpMap/SharpMap#56]
Hello:
        I  use SharpMap v1.1 to Render and Display a tif with SharpMap.Extensions.GdalRasterLayer .
       When I open a RasterFile (.tif) with chinese-character fileName，it occur  Exception with the file is not exit in the hardDisk
![default](https://cloud.githubusercontent.com/assets/28552700/25834537/3885b500-34ab-11e7-85cf-871655464156.png)
Exception Message:
/------------------------------------------------------------------------------------------------------
Couldn't load C:\Users\Administrator\Desktop\DataDemo\新建文件夹\798-505\白博文.tif

`C:\Users\Administrator\Desktop\DataDemo\鏂板缓鏂囦欢澶筡798-505\鐧藉崥鏂?tif' does not exist in the file system,
and is not recognised as a supported dataset name.
/---------------------------------------------------------------------------------------------------------
I serach for the answer and fount it come from gdalv1.9.2  gdal_csharp.dll,  who case zhe exption with Encoding.Default ->Encoding.utf8, then   make chinese-character bad.
So I  rebuilt gdal1.9.2 and  replace the gdal19.dll gdal_csharp.dll gdal_wrap.dll gdalconst_csharp.dll
gdalconst_wrap.dll  ogr_csharp.dll  ogr_wrap.dll osr_csharp.dll osr_wrap.dll  in Sharp.Extension folder
In a project I use them  but Invaid, It occur other Exception "SharpMap.Layers.GdalRasterLayer Init Exception"
LIKE this
![default](https://cloud.githubusercontent.com/assets/28552700/25834981/fc1f9218-34ad-11e7-9d56-c972d78af46e.png)

How can I do ?

**Comment by FObermaier** [comment]
If you compile SharpMap yourself you will use GDAL v1.11.

**Comment by bowen2018** [comment]
If I only want to recompile GDAL to repair the problem and use the office SharpMap.dll, which GDAL version should I  can use. And how  associate the Gdal and SharpMap?

**Comment by FObermaier** [comment]
That probably won't work at all.
The minimum effort you have to take is:
* grab the [code at that goes along with v1.1](https://github.com/SharpMap/SharpMap/archive/v1.1.zip)
* update GDAL package in the `SharpMap.Extensions` project
* compile `SharpMap.Extensions` and use just that.
