### ISSUE TITLE
Slow layer rendering

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#58]
Dear Gurus!
    There was no problem with rendering labelLayers for polygon or point layers.  But for line layer rendering is very long. There are about 300 rows for  roads (line layer) with there labels (the picture attached) , and time for rendering is about 120 seconds.  

![labelsproblem](https://cloud.githubusercontent.com/assets/3097213/26241461/6c0d6d48-3c8d-11e7-94a7-de754b37caf0.jpeg)
   The code is:
`        private void setLabelLineLayer()
        {
            labelLayer = new LabelLayer(v_layer.LayerName.Trim() + "Label");
            labelLayer.Enabled = v_layer.Enabled;
            labelLayer.LabelColumn = m_layer.labelFieldName;
            labelLayer.DataSource = v_layer.DataSource; 
            labelLayer.Theme = CreateTheme();
        }
        private static ITheme CreateTheme()
        {
            return new CustomTheme(StyleBasedOnAlignment);
        }

        private static IStyle StyleBasedOnAlignment(SharpMap.Data.FeatureDataRow dr)
        {
            var style = new LabelStyle
            {
                HorizontalAlignment = LabelStyle.HorizontalAlignmentEnum.Center,
                VerticalAlignment = LabelStyle.VerticalAlignmentEnum.Middle, 
                Rotation = -20,
                BackColor = Brushes.Pink,
                Halo = new Pen(Brushes.LightBlue, 2)
            };
            return style;
        }
`
What I can do to reduce rendering time?

**Comment by aviabunin** [comment]
P.S. 	SharpMap 1.1
Feb 11, 2014, Stable
[Uploading _roads.zip…]()
This is shape file of roads

**Comment by aviabunin** [comment]
The same problem with states of Karelia shape file - there are less then 20 lines and rendering time is about 2 minutes.   - [shape file of state borders is here](https://cloud.mail.ru/public/Dsyb/eBZXFMFws) and shape file of roads here  [line layer for roads of Karelia](https://cloud.mail.ru/public/GEz8/Jwg8ovxTk)

**Comment by aviabunin** [comment]
The main delay is in DrawString procedure 

`public static void DrawString(this Graphics self, Pen halo, Brush fill, string text, FontFamily fontFamily, int style, float emSize, StringFormat format, bool ignoreLength, GraphicsPath path)
        {
            if (path == null || path.PointCount == 0)
                return;

            var gp = new GraphicsPath();
            gp.AddString(text, fontFamily, style, emSize, new Point(0, 0), format);

            SortedList<float, GraphSegment> edges;
            var totalLength = GetPathLength(path, out edges);

            var warpedPath = PrepareTextPathToWarp(gp, totalLength, ignoreLength, format);

            if (warpedPath != null)
            {
                var wp = Warp(path, warpedPath, false, 0f);
                if (wp != null)
                {
                    if (halo != null)
                        self.DrawPath(halo, wp);
                    if (fill != null)
                        self.FillPath(fill, wp);
                    wp.Dispose();
                }
                warpedPath.Dispose();
            }
            gp.Dispose();
        }`

namely when calculating
```
var totalLength = GetPathLength(path, out edges);
var wp = Warp(path, warpedPath, false, 0f);
```
In state borders line layer each line may has  about several thousands points
This is the problem. In case the line contains many points - the time for drawing a line with labels - slows down impermissibly. It is necessary to draw labels through some distances by turning the label entirely, it seems to me, and not to draw each letter separately.

**Comment by aviabunin** [comment]
Some examples. [Roads with SharpMap
](https://cloud.mail.ru/public/3yeG/eSDdgy5gA)    [states with SharpMap](https://cloud.mail.ru/public/Dsyb/eBZXFMFws) [roads with arcgis](https://cloud.mail.ru/public/N7ry/3g5FeF7Lr)  [roads with OSM](https://cloud.mail.ru/public/Hbzu/xR4tYQztP) I would prefer a style like in OSM. Any ideas how to do this style in sharpmap?

**Comment by aviabunin** [comment]
The label is built along the border of the poligon , although 
          `style.IsTextOnPath == false. `
Is it correct?

```C#
private static BaseLabel CreateLabel(FeatureDataRow fdr, IGeometry feature, string text, float rotation, int priority, LabelStyle style, MapViewport map, Graphics g, GetLocationMethod _getLocationMethod)
        {
            if (feature == null) return null;

            BaseLabel lbl = null;
            var font = style.GetFontForGraphics(g);

            SizeF size = VectorRenderer.SizeOfString(g, text, font);

            if (feature is ILineal)
            {
                var line = feature as ILineString;
                if (line != null)
                {
                    if (style.IsTextOnPath == false)        // ? IS IT CORRECT
                    {
                        if (size.Width < 0.95 * line.Length / map.PixelWidth || style.IgnoreLength)
                        {
                            var positiveLineString = PositiveLineString(line, false);
                            var lineStringPath = LineStringToPath(positiveLineString, map /*, false*/);
                            var rect = lineStringPath.GetBounds();

                            if (style.CollisionDetection && !style.CollisionBuffer.IsEmpty)
                            {
                                var cbx = style.CollisionBuffer.Width;
                                var cby = style.CollisionBuffer.Height;
                                rect.Inflate(2 * cbx, 2 * cby);
                                rect.Offset(-cbx, -cby);
                            }
                            var labelBox = new LabelBox(rect);

                            lbl = new PathLabel(text, lineStringPath, 0, priority, labelBox, style);
                        }
                    }
                    else
                    {
                        //get centriod
                        System.Drawing.PointF position2 = map.WorldToImage(feature.EnvelopeInternal.Centre);
                        lbl = new Label(text, position2, rotation, priority, style);
                        if (size.Width < 0.95 * line.Length / map.PixelWidth || !style.IgnoreLength)
                        {
                            CalculateLabelAroundOnLineString(line, ref lbl, map, g, size);
                        }
                    }
                }
                return lbl;
            }
```

**Comment by ekoswr** [comment]
Dear Felix and Sharpmap Gurus

Thank you so much for the great code you made and maintain so far.
I have the same problem with aviabunin, when i try to load arond 10,000 points or more on the map.  we have feature on our map applications to show the vehicle's GPS coordinate history along the road and when we reach to around 10,000 points, the map form is become very slow and sometime not responding when we do the zoom or pan. Other than the point we also have polygon, circle and line layer but not as much as the GPS points layer. we taken the data from MSSQL.

<img width="866" alt="11000 Records" src="https://user-images.githubusercontent.com/22375717/56865995-9988cd80-69fe-11e9-9c52-4e34136a14d7.png">

the code listing to load the GPS layer is below. 

```
public static void AddGPSHistoryLayerFromFeature(SharpMap.Map aMapParent, SharpMap.Data.FeatureDataTable aFeature, bool aVisible)
        {
            MineDispatch.Helper.MapControls.RemoveLayer(aMapParent, "GPSHistory");

            if (aFeature != null)
            {
                try
                {
                    SharpMap.Layers.VectorLayer vlHistory = new SharpMap.Layers.VectorLayer("GPSHistory");
                    vlHistory.DataSource = new SharpMap.Data.Providers.DataTableFeatureProvider(aFeature);
                    vlHistory.Visible = aVisible;
                    vlHistory.SRID = mapSrid;
                    vlHistory.Theme = new SharpMap.Rendering.Thematics.CustomTheme(
                        new SharpMap.Rendering.Thematics.CustomTheme.GetStyleMethod(GetGPSPointCustomStyle));
                    vlHistory.ShowInLegend = false;
                    aMapParent.Layers.Add(vlHistory);
                }
                catch (Exception ex)
                {
                    string exMsg = ex.Message;
                    if (ex.InnerException != null)
                    {
                        exMsg += "\r\nInner Exception:\r\n" +
                            ex.InnerException
                            + "\r\n"
                            + ex.InnerException.StackTrace;
                    }

                    MineDispatch.Helper.ErrorLog.WriteToLog("AppException", "[MapControls.AddGPSHistoryLayerFromFeature] " + exMsg);
                }
            }
        }
```

I desperately need this problem to be solve, please let me know what i need to provide in order for you and Sharpmap gurus to help me.
Many Thanks!

**Comment by FObermaier** [comment]
Instead of using a VectorLayer with a custom theme create a seperate layer that focuses on just your `GPSHistoryData`. There are implementations that use `OpenGL` or `SharpDX` for a better rendering performance of puntal data. But the actual implmentation is usually specific to the purpose.

**Comment by ekoswr** [comment]
Felix, thank you for your advise. we will do some research on OpenGL and SharpDX

**Comment by FObermaier** [comment]
@ekoswr for further exchange on your issue please use SharpMap/SharpMap.DeltaShell#1

**Comment by ekoswr** [comment]
Felix. ok understood. thanks for advise.
