### ISSUE TITLE
How to determine the coordinates of a point at a given distance from the beginning of a line

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#59]
Dear, Gurus!
Is there any tool for finding the coordinates of a point at a given distance from  the beginning of a line (for example, a road)? Any ideas?

**Comment by becio** [comment]
The equation of the road, considered a straight line in an Euclidean space, for short distances is ok, is:

_(y-y1)/(y2-y1)=(x-x1)/(x2-x1)_

so the coordinates of a point in that line are: 

```
x = x1 + (d-d1)*(x2-x1)/(d2-d1) 
y = y1 + (d-d1)*(y2-y1)/(d2-d1)
```

where d is the measure of distance at the given point, while d1 and d2 are the measure of distance at the ends of the line. Such measure can be kilometers for example.

**Comment by FObermaier** [comment]
Check out the `LinearReferencing` namespace of `NetTopologySuite`.

**Comment by aviabunin** [comment]
Thank you very much, that's just what I wanted!
