### ISSUE TITLE
What is the appropriate way to calculate the physical length of the line and area of the polygon

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#60]
What is a proper way to calculate a phisical length of the line or area of the polygon (in Mercator projection , for example)?
Is there any tools in the SharpMap?

**Comment by FObermaier** [comment]
SharpMap uses `GeoAPI.Geometries.IGeometry` as geometry objects.
They do have a `Length` and an `Area` property. If you have projected coordinates these should be in the dimension of the coordinates. If you have geographic coordinates these values are nonsense.
You have to project them to a suitable coordinate system an get those values then.

**Comment by FObermaier** [comment]
This particular CRS is not very accurate the further away you are from the equator.

**Comment by aviabunin** [comment]
The  first version of the system will be for the Republic of Karelia (60 ° -66 ° N) No time to change coordinate system. Then, if it is for the whole of Russia - I'll take a look

![monitor](https://user-images.githubusercontent.com/3097213/27539134-f485c7ce-5a83-11e7-888c-af9daca9df86.jpeg)

**Comment by aviabunin** [comment]
It seems that the calculation of the length (area) in coordinate system 3857 does not give sufficient accuracy. Is it correct, that for more accurately calculation the length (or area) of the object, it is necessary to reproject the line (polygon) to another coordinate system (just for this concrete operation) and then turn to the calculation procedure for length (area)?

**Comment by FObermaier** [comment]
> Is it correct, that for more accurately calculation the length (or area) of the object, it is necessary to reproject the line (polygon) to another coordinate system (just for this concrete operation) and then turn to the calculation procedure for length (area)?

Yes

**Comment by aviabunin** [comment]
Is there any library to reproject IGeomery?

**Comment by aviabunin** [comment]
I meant something like  this  https://github.com/jorik041/sharpmap/blob/master/SharpMap/SpatialReference/Reprojector.cs

**Comment by aviabunin** [comment]
The problem solves GeometryTransform class in GeoAPI.CoordinateSystems.Transformations namespace. For example:
```C#
        public static IGeometry ReprojectGeometry(IGeometry ln)
        {

            GeoAPI.CoordinateSystems.ICoordinateSystem source = ProjNet.CoordinateSystems.ProjectedCoordinateSystem.WebMercator;
            
            const string wkt28406 = "PROJCS[\"Pulkovo 1942 / Gauss-Kruger zone 6\",GEOGCS[\"Pulkovo 1942\",DATUM[\"D_Pulkovo_1942\",SPHEROID[\"Krassowsky_1940\",6378245,298.3]],PRIMEM[\"Greenwich\",0],UNIT[\"Degree\",0.017453292519943295]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"latitude_of_origin\",0],PARAMETER[\"central_meridian\",33],PARAMETER[\"scale_factor\",1],PARAMETER[\"false_easting\",6500000],PARAMETER[\"false_northing\",0],UNIT[\"Meter\",1]]";
            ProjNet.CoordinateSystems.CoordinateSystemFactory cFac = new ProjNet.CoordinateSystems.CoordinateSystemFactory();
            var target = cFac.CreateFromWkt(wkt28406);

            var ctFactory = new ProjNet.CoordinateSystems.Transformations.CoordinateTransformationFactory();
            var ct = ctFactory.CreateFromCoordinateSystems(source, target);
            var targetGeomFactory = GeoAPI.GeometryServiceProvider.Instance.CreateGeometryFactory((int)target.AuthorityCode);

            IGeometry geomPulkovo = (IGeometry)GeoAPI.CoordinateSystems.Transformations.GeometryTransform.TransformGeometry(ln, ct.MathTransform, targetGeomFactory);
            return geomPulkovo;
        }
```
After the transformation, we obtain the correct geometry length (area) like this:

```C#
            var lnn = ReprojectGeometry(fdr.Geometry);
            double newroadLength = lnn.Length;
```

Problem solved.
Thank you very much!
