### ISSUE TITLE
Label Position is wrong in polygon

### ISSUE THREAD

**Issue by luo4567** [SharpMap/SharpMap#62]
I open the shp in ArcMap like this
![image](https://user-images.githubusercontent.com/7789211/27894715-7e77cafe-6240-11e7-8d3f-3c8c445ae2e9.png)
But I use openlayers to show the wms map like this
![image](https://user-images.githubusercontent.com/7789211/27894765-c59be866-6240-11e7-82d0-2602632f782d.png)
what's wrong?

**Comment by FObermaier** [comment]
Please provide the code you used to create the map. Without it, we can only guess what is wrong.

**Comment by luo4567** [comment]
this is how I add the labelLayer,and return the map to the OpenLayers.Layer.WMS
![image](https://user-images.githubusercontent.com/7789211/27940260-38efe5ea-62fc-11e7-8f00-48b2e2d62fbb.png)
openlayers code
![image](https://user-images.githubusercontent.com/7789211/27940361-bec55830-62fc-11e7-9f2e-f37479ac0dbb.png)
I do nothing except this!

**Comment by FObermaier** [comment]
I assume you have `MULTIPOLYGON` geometries. If that is the case, be sure to set
```C#
labelLayer.MultipartGeometryBehaviour = MultipartGeometryBehaviourEnum.All;
```
You can also try to adjust the label placement by assigning this delegate:
```C#
labelLayer.GetLabelLocation = (fdr) => fdr.Geometry.PointOnSurface.Coordinate;
```    
If that does not help it would be good if you could share the shapefile data.

**Comment by luo4567** [comment]
labelLayer.MultipartGeometryBehaviour = MultipartGeometryBehaviourEnum.All; it's not working！
labelLayer does not provide the 'GetLabelLocation' Method!
labelLayer.LabelPositionDelegate = (fdr) => fdr.Geometry.PointOnSurface.Coordinate;  it works a lot!
but something still wrong!
![image](https://user-images.githubusercontent.com/7789211/27952257-46059d5e-633a-11e7-9bd8-aa8ac2472ecd.png)


I use the version 3.0.0.0

**Comment by FObermaier** [comment]
We need to see the shapefile.

**Comment by luo4567** [comment]
[Shp.zip](https://github.com/SharpMap/SharpMap/files/1134296/Shp.zip)



I dissolve the map! now it renders like this
![image](https://user-images.githubusercontent.com/7789211/28000939-8d318b34-655b-11e7-808d-fba6dff6fb83.png)
