### ISSUE TITLE
Map Image not rendering in  imagebutton

### ISSUE THREAD

**Issue by nagarajmp** [SharpMap/SharpMap#63]
Hi All,

I have a problem while rendering map image to the image button. The image button appears blank when i load the form. I am using the following code to generate map.

```C#
private void GenerateMap()
{
    //Save the current mapcenter and zoom in the viewstate
    ViewState.Add("mapCenter", myMap.Center);
    ViewState.Add("mapZoom", myMap.Zoom);
    //Render map
    System.Drawing.Image img = myMap.GetMap();
    string imgID = SharpMap.Web.Caching.InsertIntoCache(1, img);
    imgMap.ImageUrl = "getmap.aspx?ID=" + HttpUtility.UrlEncode(imgID);             
}
```

This works fine when i run the code in my machine. But when i host it in server i am not able to see the map. below the screen shot of issue.
![screenshot-sharpmap](https://user-images.githubusercontent.com/19570588/28016347-99cce3ee-6591-11e7-8a16-102eb79e1570.png)

When i inspect through browser , in console it shows following messages 

1> GET http://abc.in/workview/getmap.aspxID=1cce5d0b6d4e4c4e958867d704c3f234 404 (Not Found)
getmap.aspx:1 

2> GET http://abc.in/workview/getmap.aspx?ID=1cce5d0b6d4e4c4e958867d704c3f234 404 (Not Found)

**Comment by FObermaier** [comment]
This is most likely a configuration issue on your production server.
