### ISSUE TITLE
mouse_move

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#64]
Hello,

i'm trying to move around a point on the map by moving the mouse. 

when i call MapBox.Refresh() in the mouse_move event the map wents blank until mouse_up.

i tried MapBox.Invalidate, application.doevents - same game.

any ideas?

**Comment by Lotto2** [comment]
Is there a sample code for drawing geometries an a SharpMap?

**Comment by terribletim** [comment]
@Lotto2  [this](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/Examples/WinFormSamples/FormDemoDrawGeometries.cs) might be what you are looking for.

**Comment by Lotto2** [comment]
Thanx a lot, this really is it!

**Comment by Lotto2** [comment]
Is there a sample for editing a geometry as well? 
-moving points of a polygon
-adding points to a line or polygon
-removing points from a line or polygon

**Comment by terribletim** [comment]
Try looking at [FormDemoDrawGeometries](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/Examples/WinFormSamples/FormDemoDrawGeometries.cs) and also see existing [Digitize Geometry toolbar](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.UI/Forms/ToolBar/MapDigitizeGeometriesToolStrip.cs)

You'll probably benefit from downloading master branch and running the WinFormSamples demo project, plus you can browse through the code to find answers to these sorts of questions.

**Comment by Lotto2** [comment]
the task would be to take a given geometry and edit it. nice would be to get - for example - a polygon shown as an area with points at the edges. click a point of an edge and move it around.

this geometry of 

mapBox1_GeometryDefined(GeoAPI.Geometries.IGeometry geometry)

can this be accessed by code directly?

**Comment by terribletim** [comment]
The buttons on the demo form are the equivalent of the Digitize Geometry toolbar. It may not be immediately apparent, but the events are handled in [MapBox control](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.UI/Forms/MapBox.cs#L2042). It's quite a clever way of making core user functionality readily re-usable.
