### ISSUE TITLE
Get the filtered Envelope using GetExtends() (or anyhing else)

### ISSUE THREAD

**Issue by theo2f** [SharpMap/SharpMap#66]

**Comment by theo2f** [comment]
Hi!
I'm using FilterDelegate to filter my shapefile.
After filter, the GetExtends() method still enveloping the full map.
The code:

var _shapeFile = new SharpMap.Data.Providers.ShapeFile("c:/Brazil", true);
_shapeFile.FilterDelegate = r => System.Convert.ToString(r["UF"]).Equals("RS");

VectorLayer newLayer = new VectorLayer("Brazil");
newLayer.DataSource = _shapeFile;

mapBox1.Map.Layers.Add(newLayer);
//mapBox1.Map.ZoomToExtents();
//mapBox1.Map.ZoomToBox(newLayer.Envelope);
mapBox1.Map.ZoomToBox(_shapeFile.GetExtents());
mapBox1.Refresh();

Have a way to solve it or it's a bug?

![brazil full.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598c89a2f8d0bc001fe60554/125516c66e82c728ace21e0d46ea869b398b8fe989fcb34fe611b2843b492d762a10e17132d0b52abd122e00560c4cab175c0b42f4f9892fafe73f22df4e17ff933c0120996048e6edc00db513b921814e80b6be8944c3ef3526e18d8e5d73.PNG)
![brazil RS State.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/598c89a2f8d0bc001fe60554/125516c66e82c728ace21e0d46ea869b398b8fe9bddaff70b05ce4916b0a65633b0ba92e7391a172fd172d030d5f4bfd480b5d43aafddd2daeb63c74830d08bf847f4366846c4ff8e7df46f554f832815d87b0b68b49c0ea3e2de48c874c381a010ac4.PNG)

**Comment by FObermaier** [comment]
For performance reasons the `ShapeFile.FilterDelegate` is not taken into account when calling `Shapefile.GetExtents()`

A way around this would be to 
- call `ShapeFile.ExecuteIntersectionQuery(ShapeFile.GetExtents(), fds = new FeatureDataSet())` having the filter set, 
- create a temporary provider based on the result (`var gfp = new GeometryFeatureProvider(fds[0])`)
- call `gfp.GetExtents()`.
