### ISSUE TITLE
PostGis-Provider on PostGres 9.6.4 and PostGis 2.3.3, error 42883: function getsrid(geometry) does not exist

### ISSUE THREAD

**Issue by Lotto2** [SharpMap/SharpMap#67]
Hello,

i'm trying to run SharpMap over a database under Postgres 9.6.4 and PostGis 2.3.3.

nothing is shown on the map. 

cause: PostGIS.cs / GetGeometriesInView

the function GetGeometriesInView throws an error trying to ExecuteReader() as shown below

```C#
var strSQL = "SELECT \"" + GeometryColumn + "\"" + _geometryCast + "::bytea AS \"_smGeom_\", getsrid(" + GeometryColumn + ") AS \"SRID\" ";
//...
using (var command = new NpgsqlCommand(strSQL, conn))
{
    using (var dr = command.ExecuteReader())
    {    /* ... */ }
}
```
 
error 42883: function getsrid(geometry) does not exist

does anyone know, what replacement under PostGis 2.3.3 exists for getsrid?

Thanx in advance;-)

**Comment by Lotto2** [comment]
Hoy, found out: st_srid. 

i'm going to try to change PostGIS.cs to support PostGIS 2.3. might take a few days.

**Comment by FObermaier** [comment]
I'm afraid, I cannot find the piece of code that you are refering to.

**Comment by Lotto2** [comment]
Can't find it in the actual source as well. Need to update. Thanks for the hint...
