### ISSUE TITLE
old versio of newtonsoft.json

### ISSUE THREAD

**Issue by jeremysimmons** [SharpMap/SharpMap#7]
https://github.com/SharpMap/SharpMap/blob/master/SharpMap/packages.config references <package id="Newtonsoft.Json" version="4.5.11" targetFramework="net40-Client" />.
Would you be open to a pull request updating to the most recent version?

Since this is potentially breaking, is this a major revision to your package 2.0.0.0 or only a minor revision? 1.2.0.0?

**Comment by FObermaier** [comment]
Which version do you consider new? It is currently at 7.01 and I'd like it to be in sync with the version NTS uses.
Be sure to look at the Branches/1.0 branch, or do you explicitly need the version in master?

**Comment by jeremysimmons** [comment]
https://www.nuget.org/packages/SharpMap/1.1.0

says 
NewtonSoft.Json (= 4.5.11)
https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.Core.nuspec
says

<dependency id="NewtonSoft.Json" version="[6.0.3]"/>

the version in the public nupkg on nuget.org is what im most onterested in updating.

what is NTS?

https://www.nuget.org/packages/SharpMap/

**Comment by jeremysimmons** [comment]
nts is https://github.com/NetTopologySuite/NetTopologySuite, correct?

**Comment by FObermaier** [comment]
NTS is NetTopologySuite

The SharpMap nuspec file has not yet been updated. The [used package](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap.Converters.GeoJSON/packages.config) is:
`<package id="Newtonsoft.Json" version="7.0.1" targetFramework="net40-client" />`

**Comment by jeremysimmons** [comment]
I'm missing it... Where does NTS depend on NewtonSoft.JSON?

https://www.nuget.org/packages/NetTopologySuite/1.14.0
GeoAPI (>= 1.7.4 && < 1.8.0
https://www.nuget.org/packages/GeoAPI/1.7.4
Dependencies
This package has no dependencies.

Are you using the 1.0 branch now, and not the master branch?

**Comment by FObermaier** [comment]
> I'm missing it... Where does NTS depend on NewtonSoft.JSON?

It is in the [NetTopologySuite.IO.GeoJSON](https://github.com/NetTopologySuite/NetTopologySuite/blob/master/NetTopologySuite.IO/NetTopologySuite.IO.GeoJSON) project which is seperate.

> Are you using the 1.0 branch now, and not the master branch?

yes

**Comment by FObermaier** [comment]
Btw, have you tried to force an update of the NewtonSoft.Json package?
`
update-package "Newtonsoft.Json -version 6.0.3 -ignoredependancies
`

**Comment by jeremysimmons** [comment]
> Btw, have you tried to force an update of the NewtonSoft.Json package?

yes I have forced an update.
it just adds an assembly binding redirect

```
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
            </dependentAssembly>
        </assemblyBinding>
    </runtime>
```

The major version number difference tells me that's unsafe/unwise to do. 

This could be fixed if the nuget.org package were updated with the current source from the 1.0 branch.
https://github.com/SharpMap/SharpMap/tree/Branches/1.0, which correctly references newtonsoft.json 7.0.0.1

The current release - https://github.com/SharpMap/SharpMap/releases/tag/v1.1 has the same issue.

**Comment by FObermaier** [comment]
SharpMap 1.2 is [work in progress](https://github.com/SharpMap/SharpMap/milestones). 
Currently I cannot tell when it will be released.

**Comment by jeremysimmons** [comment]
sounds like my choices are to help you close out those last three bugs. Or do a private compile and release on our internal Nugett server.

no chance you'd want to re-release to Nugett with the Newton soft json 7.0 reference before the 1.2 release is there? even for beer money?

**Comment by Matti-Koopa** [comment]
The NuGet package forces the old Version of Newtonsoft.Json which makes it icompatible with my project, which uses a newer one already.

Please change the requirement, to support any version >= 4.5.11 instead of forcing = 4.5.11.

**Comment by becio** [comment]
+1 for the update, meanwhile a workaround is to embed the conflicting assembly as resource of your project and using AppDomain.AssemblyResolve event to load it, this way you can have multiple versions.
