### ISSUE TITLE
Raster symbolizer example

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#70]
Hi,
Can any one please share a sample of how to symbolize raster layers using sharpmap?For instance, I have a DEM file which I can open using gdal extension but how can I colorize it?

**Comment by FObermaier** [comment]
Have a look at the `WinFormSamples` [project](https://github.com/SharpMap/SharpMap/tree/Branches/1.0/Examples/WinFormSamples/GeoData/VRT). You may need a virtual raster file.

**Comment by am2222** [comment]
@FObermaier Hi, Thanks very much, it seems sharp map can only render vrt files but can not symbolizer normal tiff files like dem

**Comment by FObermaier** [comment]
The vrt (virtual raster file) approach should work with tiff files as well.
As you can see by looking at the file, it refers to some other raster file that is of the ASC format.

**Comment by am2222** [comment]
@FObermaier  thanks very much
