### ISSUE TITLE
How to copy image from raster layer

### ISSUE THREAD

**Issue by aviabunin** [SharpMap/SharpMap#71]
Hi, I am trying to copy image from raster layer to file. The initial image looks like this:
![topo ptrscr](https://user-images.githubusercontent.com/3097213/33018842-0db22514-ce09-11e7-8458-4b6b63e2c134.png). 
     With next code to save image:
```C#
Image img = mapBox1.Map.GetMap(96);
SaveFileDialog saveFileDialog1 = new SaveFileDialog();
saveFileDialog1.InitialDirectory = @"D:\myImages";
saveFileDialog1.Filter = "JPeg Image|*.jpg";
saveFileDialog1.Title = "Save an Image File";
saveFileDialog1.ShowDialog();

if (saveFileDialog1.FileName != "")
{
    System.IO.FileStream fs = (System.IO.FileStream)saveFileDialog1.OpenFile();
    img.Save(fs, System.Drawing.Imaging.ImageFormat.Jpeg);
    fs.Close();
}
```
I get the wrong picture like this:
![topo getmap](https://user-images.githubusercontent.com/3097213/33019221-797dd22e-ce0a-11e7-9610-7efc53e7ac82.jpg)
In the bottom of image ( ~ 0.5 inch higher ) we see the boundary between the two parts of the picture. 
The bottom part of the picture is offset from the top.
This parts are taken from 2 different  .ecw  files. 
    The image in the first figure is obtained with the help of the **prtscr** operation. 
    How to get around this problem?

**Comment by aviabunin** [comment]
Although if I use a different resolution (300 dpi), then the picture is correct:
![topo6](https://user-images.githubusercontent.com/3097213/33019914-536339fa-ce0d-11e7-8758-e234ef5529ba.jpg)

**Comment by aviabunin** [comment]
While it was not possible to understand when it prints correctly and when it crashes. On both scales can print correctly or not

**Comment by FObermaier** [comment]
I use the `Map.GetMap()` function a lot to copy the map image to the clipboard and have not had the issue you are describing here. Maybe there is sth going on with the map behind the scene?

Have you tried to get the map image using a clone of the map?
```C#
var tmpMap = mapBox1.Map.Clone();
Image img = tmpMap.GetMap(96);
//tmpMap.DisposeLayersOnDispose = false;
tmpMap.Dispose();

// Your code to save the image follows
```

**Comment by aviabunin** [comment]
Sharpmap is excellent ! Thank you very much, Felix!
