### ISSUE TITLE
can not render a shp layer

### ISSUE THREAD

**Issue by jieqin1987** [SharpMap/SharpMap#72]
I use sharpmap render a shp layer as bellow：
The Gfi contains the feature of the shp file
```C#
VectorLayer layCountries = new VectorLayer("CollectPoints");
string fileName = FNGlobal.STR_RootDir + @"/Data/dem.shp";
layCountries.DataSource = new ShapeFile(fileName, true);
try
{
    Dictionary<double, SharpMap.Styles.IStyle> styles =
    new Dictionary<double, SharpMap.Styles.IStyle>();

    for (int i = 0; i < Gfi.FeatureValues.Count; i++)
    {
        double height = Gfi.FeatureValues[i];
        if ((height > Gfi.MaxValue) || (height < Gfi.MinValue))
            height = AverageHeight;
        int index = (int)((height - Gfi.MinValue) / ((Gfi.MaxValue - Gfi.MinValue) / ColorNum));
        if (index >= ColorNum)
            index = ColorNum - 1;
        SharpMap.Styles.VectorStyle vs = new SharpMap.Styles.VectorStyle();
        Color c = Properties.Resources.BaseColor.GetPixel(index * 20 + 2, 1);
        vs.Fill = new SolidBrush(c);
        vs.EnableOutline = false;
        vs.Outline = new Pen(Brushes.Black, 1.2f);
        if (!styles.ContainsKey(height))
            styles.Add(height, vs);
    }
    SharpMap.Styles.VectorStyle style1 = new SharpMap.Styles.VectorStyle();
    style1.Fill = new SolidBrush(Color.FromArgb(204, 89, 68));
    style1.EnableOutline = false;
    style1.Outline = new Pen(Brushes.Black, 1.2f);

    SharpMap.Rendering.Thematics.ITheme theme =
    new SharpMap.Rendering.Thematics.UniqueValuesTheme<double>("Height", styles, style1);
    layCountries.Theme = theme;
    layCountries.SRID = 4326;
    MapImageAddLayer(layCountries);
    MoveMap((GeoPoint)Gfi.CenterPoint);

    MapImageRefresh();
    MessageBox.Show(mapImage1.Map.Layers.Count.ToString());
}
catch (Exception ex)
{
    Logger.Instance.Info("load dem error" + ex.ToString());
}
```
then I get error info like this：
```
System.ArgumentException: Invalid record requested at index 3200
   在 SharpMap.Data.Providers.DbaseReader.set_CurrentRecordOid(UInt32 value)
   在 SharpMap.Data.Providers.DbaseReader.GetValues(UInt32 rowid)
   在 SharpMap.Data.Providers.ShapeFile.ExecuteIntersectionQuery(Envelope bbox, FeatureDataSet ds)
   在 SharpMap.Layers.VectorLayer.RenderInternal(Graphics g, Map map, Envelope envelope, ITheme theme)
   在 SharpMap.Layers.VectorLayer.Render(Graphics g, Map map)
   在 SharpMap.Map.RenderMap(Graphics g, LayerCollectionType layerCollectionType, Boolean drawMapDecorations, Boolean drawTransparent)
```

And the shp file can be render well by the QGIS.

**Comment by FObermaier** [comment]
How many features does your ShapeFile have?
Does the dBase-File (dbf) contain as many records?
Does QGIS yield proper values for the shape with the OID 3200?

**Comment by jieqin1987** [comment]
My dbf file like this
![image](https://user-images.githubusercontent.com/16496446/33551808-83eaa54c-d92d-11e7-9227-929df3b594dd.png)
![image](https://user-images.githubusercontent.com/16496446/33551834-977e2e4e-d92d-11e7-839e-65e059b50681.png)
form 0 to 3199 total 3200 features

**Comment by FObermaier** [comment]
Leaves the question how many features your ShapeFile has?

**Comment by jieqin1987** [comment]
3200 features

**Comment by jieqin1987** [comment]
![image](https://user-images.githubusercontent.com/16496446/33554228-d1e36104-d936-11e7-8ea4-9782740f1941.png)

**Comment by jieqin1987** [comment]
I read the shp file by GDAL and get the file info as the picture show

**Comment by jieqin1987** [comment]
I can not upload the shp file in this page , how can I transmit the file to you

**Comment by FObermaier** [comment]
What does `new ShapeFile(fileName, true).GetFeatureCount()` say?

**Comment by jieqin1987** [comment]
3200

**Comment by FObermaier** [comment]
Please add SHP, SHX, PRJ and DBF file of your Shapefile file-set to a ZIP file and supply it with this issue.
([see this](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/))

**Comment by jieqin1987** [comment]
I have found the bug
string fileName = FNGlobal.STR_RootDir + @"/Data/dem.shp";
            VectorLayer layCountries = new VectorLayer("Countries");
            layCountries.DataSource = new ShapeFile(fileName, false);
the second parameter of ShapeFile must be set false. Then it is ok.
[dem.zip](https://github.com/SharpMap/SharpMap/files/1533980/dem.zip)
