### ISSUE TITLE
Sharpmap WPF control does not behave in a fully WPF-compatible fashion

### ISSUE THREAD

**Issue by glenatron** [SharpMap/SharpMap#75]
As far as I can tell the SharpMap WPF control is effectively a WindowsFormsHost customised to work with the SharpMap forms controls. Consequently the control doesn't really fit well with the WPF rendering approach and one can't overlay controls and so on.

Is there a technical reason that the a set of WPF layer providers have not been created to allow a more compliant experience for WPF developers or is it just a matter of lack of demand?

Edited to add: Looks like the GDI+ rendering approach is tied pretty heavily into the layers, but not inextricably so as far as I can judge.

**Comment by glenatron** [comment]
I am looking at decoupling the rendering from the Graphics object in the hope I can try working with an alternative renderer - is there any kind of list, forum or Slack channel associated with the project where I can ask about any problems I run into or things I don't understand in the existing codebase?

**Comment by FObermaier** [comment]
I'm currently looking into replacing usage of `System.Drawing` with `SkiaSharp` or `SixLabors.ImageSharp`.

We might as well make the renderer plugable, in that case we'd need the drawing primitives (`Point`, `Rectangle`, `Color`, `Pen`, `Brush`, `Font`, `Path` ...) inside SharpMap.

I'll try to listen to https://gitter.im/SharpMap

**Comment by FObermaier** [comment]
It is being used in production.
