### ISSUE TITLE
Labels over multiple lines

### ISSUE THREAD

**Issue by dylanparry** [SharpMap/SharpMap#77]
I've been trying to figure out if it's possible to add a line break to a label. I've tried adding `\r\n` and `<br>` to the text used for the label, but they just render those strings as part of the label. I have some maps that are bilingual, and the labels have some place names that are different in the two languages, so I was hoping I could write one language on one line, then the other on a second line. Is this possible?

**Comment by FObermaier** [comment]
According to the result of [UnitTests.Layers.LabelLayerTest](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/UnitTests/Layers/LabelLayerTest.cs) this should be possible:
![MultiLineCenterAligned](https://user-images.githubusercontent.com/2065346/71174844-6ed9d680-2266-11ea-8c23-20c6fb83b045.png)

Forcing a new line break is done with `\n`.
https://github.com/SharpMap/SharpMap/blob/b89c4fb4fb873ba7d0d43c322eaf732e0fb41a9d/UnitTests/Layers/LabelLayerTest.cs#L31-L40
