### ISSUE TITLE
GDALRasterLayer calculates wrong boundries

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#81]
Hi,
While I was trying to add a landsats tif file intomap using GDALRASTERLAYER I faced an strange error,
In this class in this function 
```
  band[i].ReadRaster((int)Math.Round(x1), (int)Math.Round(y1), (int)Math.Round(imgPixWidth),
                                               (int)Math.Round(imgPixHeight),
                                               buffer[i], (int)Math.Round(dblImginMapW), (int)Math.Round(dblImginMapH),
                                               0, 0);
```

it returns 

```
band 1: Access window out of range in RasterIO().  
Requested\n(520086,4227731) of size 221430x161263 on raster of 7381x7361."
```

It seems it is calculates boundries wrong, I tried to reproject raster to 3857, or change maps projection to 4326 but nothing changed, 
The strange part is that it works fine with other rasters. I have no idea why this problem happens, could it be because of big tif size?

**Comment by FObermaier** [comment]
I suppose the "bits per pixel" is computed wrong.
Could you share the TIFF or a part of it?

**Comment by am2222** [comment]
@FObermaier  It is a normal landsat 8 tif file. I tried with a vrt too but it was the same, I am uploading it now. I'll share it when it finished.

**Comment by am2222** [comment]
@FObermaier  Here you can find a download link of landsat tif https://mega.nz/#!81FDETRL!sYbtIRQutrBVVqR_y4MyFqxhH8S09Gl-1L04dC4L37M

**Comment by am2222** [comment]
@FObermaier  could it be because of SRID?

**Comment by am2222** [comment]
@FObermaier Hi,
Based on my investigations I found that the number of `x1` and `y1` are calculated wrong, I noticed that you are hard coding geotransform by these values

`geoTrans = new[] { 999.5, 1, 0, 1000.5, 0, -1 };`

and have used them in these functions

```
geoTransform.PixelX(left)
geoTransform.PixelY(top)
```

later you have used 

`        public double PixelX(double lat)
        {
            return (_transform[0] - lat) / (_transform[1] - _transform[2]);
        }
`

Does `PixelX` is safe with all `SRID`s? and the error could raise because of `999.5` and `1000.5` when input images pixels are greater than these numbers?

**Comment by FObermaier** [comment]
To reproduce this, could you share the code you use to display the file,
especially 
* viewport of the map
* SRID of map   

Additionally everything you do to configure the `GdalImageLayer`, esp.
* CoordinateTransformation
* SRID
* BitSize

**Comment by am2222** [comment]
@FObermaier  I just used the example of windows forms (GDALSample.cs) .  I just used these to create layer.

```
map.SRID = 4326;
                SharpMap.Layers.GdalRasterLayer layer;

                layer = new SharpMap.Layers.GdalRasterLayer("GeoTiff", @"E:\Personal\Project\Ghasemzade\DemoData\LC81680342013097LGN01\LC81680342013097LGN01_B2.TIF");
                layer.UseRotation = false;
                layer.SRID = 4326;
```
I did not changed `bitdepth` parameter or coordinate transform.
Do I miss some other configurations?

---
I noticed that setting this parameters prevents using  

`geoTrans = new[] { 999.5, 1, 0, 1000.5, 0, -1 };` and loads maps
```

            layer.UseRotation = false;
            layer.SRID = 32638;
            layer.HaveSpot = true;
```

I have not tested the sitution where maps `SRID` is different then images `SRID`

**Comment by FObermaier** [comment]
There are several issues with your code:
* the image (i assume it is the one you posted previously) has a projection with the SRID 32638.
* the image has a BitDepth of 16
* to reproject the image to EPSG:4326 you need to call `layer.ReprojectToMap(map);`
* Don't set `layer.UseRotation` to `false`

**Comment by am2222** [comment]
@FObermaier  thanks very much. it worked. but it does not show any thing when maps projection is diffrent from images projection.but this not any problem. I have faced another problem which I think is because of wrong no value data. sharpmap draws image as a black rectangular . I have set its novalue data (it is 0 0 0  for an rgb image) but nothing changed
