### ISSUE TITLE
How to show it directly with latitude and longitude

### ISSUE THREAD

**Issue by caiyusheng** [SharpMap/SharpMap#82]
How to show it directly with latitude and longitude

**Comment by am2222** [comment]
@caiyusheng  show what?you want to zoom to a lat,lon?

**Comment by caiyusheng** [comment]
@am2222  
It shows X, Y coordinates, and I want to get the latitude and longitude of the earth.

**Comment by am2222** [comment]
well it is just a simple SRC convert, this link might help you 

https://stackoverflow.com/questions/14329691/convert-latitude-longitude-point-to-a-pixels-x-y-on-mercator-projection

**Comment by caiyusheng** [comment]
THKS
