### ISSUE TITLE
InvalidOperationException - object is currently in use elsewhere in wmslayer

### ISSUE THREAD

**Issue by am2222** [SharpMap/SharpMap#86]
Hi,
It when we set `Opacity` parameter for a wms and use it with `AsyncLayerProxyLayer` an error happens in GDI+ which indicates that `InvalidOperationException - object is currently in use elsewhere ` it refers to  `_imageAttributes` which could not be used among different processes. I tried to change `wmslayer` class and added  this part into `render` function:

```C#
if (_imageAttributes != null)
    lock (_imageAttributes)
    {
        //https://stackoverflow.com/questions/1851292/invalidoperationexception-object-is-currently-in-use-elsewhere
        g.DrawImage(img, new Rectangle(0, 0, img.Width, img.Height), 0, 0,
        img.Width, img.Height, GraphicsUnit.Pixel, _imageAttributes);
    }
```
It works fine now.  I have no idea if it conflicts with other parts or not

**Comment by FObermaier** [comment]
@am2222, thanks for the hint.
I chose to fix it by creating a new `ImageAttributes` class for rendering when `Opacity` < 1.
Please see b80fbd589de453b771e0c6b8fcc30c838159ad66
