### ISSUE TITLE
Update Newtonsoft.Json & BruTile

### ISSUE THREAD

**Issue by TannerBragg** [SharpMap/SharpMap#92]
(I really don't want to come off as whiny, but this is becoming quite the nuisance.)

You guys have commented before that you are trying to stay with the same version of BruTile and Newtonsoft.Json as the GeoApi dependency; however, this is starting to become a little difficult to accommodate.  

SharpMap is many versions behind and it would be very nice if SharpMap came up to later versions.  As it stands now, I cannot use the SharpMap nuget package because of these version conflicts.  I have to build SharpMap separately in it's own solution and include the DLL in my solution.

Is this something that could be possible in SharpMap's future?  What are some approaches we could take to alleviate?  Do we need to offer to update GeoApi library?

**Comment by terribletim** [comment]
@FObermaier @pauldendulk I'm working on some updates at the moment. SharpMap SLN currently using **BruTile** and **BruTile.Desktop** `0.18.1`. Is it ok if I update to `2.0.1`? A quick check of dependencies shows NetFramework >= 4.5 and NetStandard >= 1.6 which should be compatible with Branches/1.0. Or is there some reason why this shouldn't be done for the time being? Thanks

**Comment by terribletim** [comment]
See explanation [here](https://github.com/SharpMap/SharpMap/issues/122#issuecomment-437904675) why BruTile hasn't been updated

**Comment by MarcoGiorgi** [comment]
I'm having the same issues, and I'm using SharpMap in a web application only to read shapefiles (not to visualize them). Which is the best way to work around the dependency issue?
