### ISSUE TITLE
RasterPointSymbolizer render error when scale != 1 or rotation is applied

### ISSUE THREAD

**Issue by terribletim** [SharpMap/SharpMap#95]
`RasterPointSymbolizer` does not render the symbol on specified point when scale != 1, or rotation is applied, as illustrated in attached diagram using a 64x64 pixel image to highlight the problem. In each case, the symbol should render centred on the graticule intersection. 

![rasterpointsymbolizer problem](https://user-images.githubusercontent.com/17949545/39674706-31830464-517a-11e8-9599-494f34b37559.png)

There are 2 parts to the problem:

Firstly, **Scale** is being applied twice at [PointSymbolizer::GetOffset](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Rendering/Symbolizer/PointSymbolizer.cs#L74) and also incorrectly at [RasterPointSymbolizer::Size](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Rendering/Symbolizer/RasterPointSymbolizer.cs#L114). Test 1 plots correctly when this is fixed.

Secondly, matrix rotation and translation is not being defined correctly in [PointSymboloizer::OnRender](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Rendering/Symbolizer/PointSymbolizer.cs#L103). Would appreciate some help on this one.

Code sample to generate image: [RasterPointSymbolizerTest.zip](https://github.com/SharpMap/SharpMap/files/1977731/RasterPointSymbolizerTest.zip)

**Comment by terribletim** [comment]
Sorry - it looks like I've messed up the PR after spending several hours trying to create a 2nd fork. 

I thought this was a dead end so went back and committed changes under 1st fork (so commit is included with existing PR) and now see that it has shows up twice.

Apologies to those who have to weed through this. For future reference, if I have commits that should be under separate PRs should I create 2nd fork, or create a branch on 1st fork?

**Comment by FObermaier** [comment]
To keep the PR focused, create a new branch off the current development branch.
If your addition requires features off of a previous PR, than you should branch off that branch.

**Comment by FObermaier** [comment]
This has been fixed with PR #91, hasn't it?

**Comment by terribletim** [comment]
Correct.
