### ISSUE TITLE
NOAA S57 files return a null DataSource on Ogr Initialization

### ISSUE THREAD

**Issue by rrbiz662** [SharpMap/SharpMap#96]
When trying to import an `S57` file downloaded from the `National Oceanic and Atmospheric Administration` (NOAA) the `OgrProvider` returns a `null` DataSource on initialization. This was noticed in the `OgrSample` of the `WinFormSamples`. 

[US1AK90M.zip](https://github.com/SharpMap/SharpMap/files/2007176/US1AK90M.zip)

**Comment by FObermaier** [comment]
Somehow IHO S-57 got lost in creating of GDAL nuget package.

**Comment by FObermaier** [comment]
Sorry, which of the files have you been trying to open?
