### ISSUE TITLE
How do I translate coordinates?

### ISSUE THREAD

**Issue by beppe9000** [SharpMap/SharpMap#97]
I would like, given a coordinate, to translate it towards another one by a determined distance.
Can this library do that? Are there alternatives?

**Comment by FObermaier** [comment]
SharpMap uses NetTopologySuite to handle geometries.
NetTopologySuite has an AffineTransformation class that can translate coordinates the way you seem to want it.
http://nettopologysuite.github.io/html/class_net_topology_suite_1_1_geometries_1_1_utilities_1_1_affine_transformation.html

**Comment by beppe9000** [comment]
Thanks! I will look into it.
