### ISSUE TITLE
VectorLayer Render issues

### ISSUE THREAD

**Issue by terribletim** [SharpMap/SharpMap#98]
Hi, and first up thanks for all the effort that has gone into SharpMap.<br/><br/>
I noted that sometimes features are not rendering with `CustomTheme`, due to `VectorLayer` incorrectly using the default style [at line 269](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L269) and not the theme style.   
I will clean up and issue PR, but **before** I do this would like confirmation on another render issue.  <br/> <br/>
When `VectorStyle` defines **Outline**, **Fill**, and **Line**, and also `EnableOutline =  true`, **polygons** are rendered as expected, but any **linestrings** will be rendered twice - once with Outline pen and once with the Line pen. I noticed this when using Outline thickness = 4 and Line thickness = 2 which causes **LineStrings** to be drawn with thickness = 4. This isn't what I want and seems rather strange - please can someone enlighten me as to what is the purpose of [IF statement at Line 400](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L400)? <br/><br/>
I've looked at the UnitTests to see if there was any validation of this as intended behavior, and couldn't find any confirmation as it seems each test is based on a single geometry type and not a mixture of geometry types which is what I'm working with.
<br/><br/>
Thanks in advance
<br/><br/>
Tim

**Comment by terribletim** [comment]
Apologies - cancel the first paragraph re Line 269. It is testing if Layer whether or not layer is enabled.

**Comment by terribletim** [comment]
Please can someone give me some direction on 2 points relating to this issue:<br/>

1.  What was the intention in LineStrings being rendered twice when `EnableOutline = true`? I'm familiar with cartographic symbology with inline / offset line techniques, but I'm not sure what was intended here - are then any samples I can refer to where `EnableOutline = true` is required to achieve a particular rendering? <br/>
2. When working with a `CustomTheme` and `EnableOutline = true`, [VectorLayer.RenderInternal (…. theme)](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L239) iterates through themes, styles, and features twice (when ). Is it worthwhile re-working this similar to rendering with `Styles` ([VectorLayer.RenderInternal](https://github.com/SharpMap/SharpMap/blob/Branches/1.0/SharpMap/Layers/VectorLayer.cs#L343)) where rendering is performed in single pass without iteration?

**Comment by FObermaier** [comment]
That SharpMap renders `LineString`s twice when `EnableOutline` is set to `true` is a feature. This way you can easily render streets/roads/rivers/... with some border, like shown in the image below:
![unbenannt](https://user-images.githubusercontent.com/2065346/42166193-84a43d22-7e0a-11e8-8c5d-95488881ed20.PNG)
The whole dataset is painted twice, in this case on the first pass with a thicker black pen that is configured in the `Outline` property of the `VectorStyle` and then with the thinner `Line` pen. If the lines were rendered immediately after each other, using `Outline` and `Line` pens the crossings would not look as nice as they do.

**Comment by terribletim** [comment]
Thanks for info. There's a bit of a conflict here - the 2 scenarios (for the benefit of anyone who is reading this at a later date) are normal rendering, or rendering by Theme.<br/><br/>

In the case of normal rendering `protected void RenderInternal(Graphics g, MapViewport map, Envelope envelope)` this could be achieved with a `GroupStyle` (skipping special handling for `EnableOutline` described above) where all features are painted in Style1, followed by all features in Style2, and so on up to StyleN. However, all features are painted in uniform manner with no attribute-based distinction (eg road classification).<br/><br/>

Rendering by Theme `protected void RenderInternal(Graphics g, MapViewport map, Envelope envelope, ITheme theme)` allows attribute-based distinction **but** `GroupStyle` will not achieve desired result for roads as each _feature_ is rendered completely in Style1, Style2.... StyleN before moving onto _next_ feature, hence special handling required for `EnableOutline` with a single style. While this is fine for _linestring_ layers, layers with both linestrings **and** polygons will not render as expected as described at top.<br/><br/>

OK - so I could do a CustomTheme to return style based upon attributes **and** geometry type but it seems kind of weird as I'm trying to do something that I think is relatively simple and common. It would ideal if `GroupStyle` could be used for both rendering types, with special handling of `EnableOutline` removed. This could be done for Themes by looping through features rendering all Style1 to image1, all Style2 to image2,.... all StyleN to imageN and then layering images. <br/><br/>
Are you open to a change along these lines or does it create too many headaches for existing maps? If you don't want any changes here then I'll sort out my problem with a CustomTheme.

**Comment by FObermaier** [comment]
> but it seems kind of weird as I'm trying to do something that I think is relatively simple and common.

What is it that you want to achieve?

**Comment by terribletim** [comment]
In a VectorLayer with linestrings and polygons, I want to render the polygons with thick outline (eg 4) and the linestrings in the same colour with thinner line (eg 2). As it stands at the moment, **EnableOutline** must be true for polygon outline to be drawn, and this results in linestrings being drawn twice - first with width 4, then with width 2 (ie end up with unwanted thick linestrings) <br/> 
This applies to both drawing by Style and by Theme. <br/>
The crux of my problem is that **EnableOutline** has been hijacked to achieve something that only works for linestring layers. My comments above are trying to find a way where special handling of **EnableOutline** can be removed but can still achieve your street-style rendering with nice line crossings (eg GroupStyles).

**Comment by FObermaier** [comment]
I was not able to determine the time when the `EnableOutline` logic for `LineString`s was introduced to SharpMap. IIRC it has been there when I started to use SharpMap. That's why I am hesistant to change it.
Mixed layers with `ILineal` and `IPolygonal` geometries are -even nowadays- rather uncommon. So generally this should cause no trouble to the general purpose user.

The simplest solution to your problem seems to me that you could create

```C#
public class TimsVectorLayer : SharpMap.Layers.VectorLayer {
    public override void Render(System.Drawing.Graphics g, SharpMap.Map.MapViewPort mvp) {
        // Your logic to render the layer goes here!
        
        // Don't forget to raise LayerRendered event, but don't call base.Render(g, mvp)!
    }
}
```
