### ISSUE TITLE
Build Assemblies

### ISSUE THREAD

**Issue by sindizzy** [SharpMap/SharpMap#99]
How exactly do you build the assemblies. I cloned the project and built it and got numerous errors. There must be a step I am missing.

**Comment by terribletim** [comment]
Have you restored NuGet packages?

**Comment by sindizzy** [comment]
I don't believe so. How do i do that? All I did was go to the main page and I chose Clone or Download>Open in Desktop. Are there instructions somewhere that I can follow?

**Comment by terribletim** [comment]
In Visual Studio, right-click on Solution and choose Restore NuGet Packages

**Comment by sindizzy** [comment]
Ok did that and response is "All packages are already installed and there is nothing to restore.". Clean solution and then rebuild solution. Got 56 errors.

**Comment by sindizzy** [comment]
Tried to download the zip file and same result. Is there a place where I can get the compiled DLLs just to test the framework?

**Comment by sindizzy** [comment]
After some research it appears the project requires C# 7.0. Opened the project in VS2017 and it compiles fine.
